Readium.Models.ManifestItem=Backbone.Model.extend({});Readium.Collections.ManifestItems=Backbone.Collection.extend({model:Readium.Models.ManifestItem});
Readium.Models.PackageDocumentBase=Backbone.Model.extend({initialize:function(){this.url=this.get("url");this.file_path=this.get("url");this.uri_obj=new URI(this.url)},jath_template:{metadata:{id:"//def:metadata/dc:identifier",epub_version:"//def:package/@version",title:"//def:metadata/dc:title",author:"//def:metadata/dc:creator",publisher:"//def:metadata/dc:publisher",description:"//def:metadata/dc:description",rights:"//def:metadata/dc:rights",language:"//def:metadata/dc:language",pubdate:"//def:metadata/dc:date",
modified_date:"//def:metadata/def:meta[@property='dcterms:modified']",layout:"//def:metadata/def:meta[@property='rendition:layout']",spread:"//def:metadata/def:meta[@property='rendition:spread']",orientation:"//def:metadata/def:meta[@property='rendition:orientation']",ncx:"//def:spine/@toc"},manifest:["//def:item",{id:"@id",href:"@href",media_type:"@media-type",properties:"@properties"}],spine:["//def:itemref",{idref:"@idref",properties:"@properties"}],bindings:["//def:bindings/def:mediaType",{handler:"@handler",
media_type:"@media-type"}]},getCoverHref:function(a){var b,c;b=a.getElementsByTagName("manifest")[0];c=$('item[properties~="cover-image"]',b);if(c.length===1&&c.attr("href"))return c.attr("href");a=$('meta[name="cover"]',a);c=a.attr("content");if(a.length===1&&c&&(c=$('item[id="'+c+'"]',b),c.length===1&&c.attr("href")))return c.attr("href");c=$("#cover",b);return c.length===1&&c.attr("href")?c.attr("href"):null},parse:function(a){var b;typeof a==="string"&&(a=(new window.DOMParser).parseFromString(a,
"text/xml"));a.evaluate?(Jath.resolver=function(a){return{def:"http://www.idpf.org/2007/opf",dc:"http://purl.org/dc/elements/1.1/"}[a]},b=Jath.parse(this.jath_template,a)):b=Readium.Utils.OPFParser(a);if(a=this.getCoverHref(a))b.metadata.cover_href=this.resolveUri(a);if(b.metadata.layout==="pre-paginated")b.metadata.fixed_layout=!0;b.manifest=new Readium.Collections.ManifestItems(b.manifest);return b},reset:function(a){this.set(this.parse(a))},resolveUri:function(a){uri=new URI(a);return uri.resolve(this.uri_obj).toString()}});
Readium.Models.ValidatedPackageMetaData=Readium.Models.PackageDocumentBase.extend({initialize:function(a,b){Readium.Models.PackageDocumentBase.prototype.initialize.call(this,a,b);this.set("package_doc_path",this.file_path)},validate:function(){},defaults:{fixed_layout:!1,open_to_spread:!1,cover_href:"/images/library/missing-cover-image.png",created_at:new Date,updated_at:new Date},parseIbooksDisplayOptions:function(a){var b=(new window.DOMParser).parseFromString(a,"text/xml"),a=b.getElementsByName("fixed-layout")[0],
b=b.getElementsByName("open-to-spread")[0];this.set({fixed_layout:a&&a.textContent.toLowerCase().trim()==="true",open_to_spread:b&&b.textContent.toLowerCase().trim()==="true"})},parse:function(a){return Readium.Models.PackageDocumentBase.prototype.parse.call(this,a).metadata},save:function(a,b){var c=this;this.set("updated_at",new Date);Lawnchair(function(){this.save(c.toJSON(),b.success)})}});
Readium.Models.PackageDocument=Readium.Models.PackageDocumentBase.extend({initialize:function(){Readium.Models.PackageDocumentBase.prototype.initialize.call(this);this.on("change:spine_position",this.onSpinePosChanged)},onSpinePosChanged:function(){this.get("spine_position")>=this.previous("spine_position")?this.trigger("increased:spine_position"):this.trigger("decreased:spine_position")},validate:function(a){if(!a.manifest&&!this.get("manifest"))return"ERROR: All ePUBs must have a manifest";var b=
a.spine||this.get("spine");if(!b)return"ERROR: All ePUBs must have a spine";if(a.spine_position<0||a.spine_position>=b.length)return"ERROR: invalid spine position"},defaults:{spine_position:0},getManifestItem:function(a){return this.getManifestItemById(this.get("spine")[a].idref)},getManifestItemById:function(a){return this.get("manifest").find(function(b){if(b.get("id")===a)return b})},currentSection:function(){return this.getManifestItem(this.get("spine_position"))},hasNextSection:function(){return this.get("spine_position")<
this.get("spine").length-1},hasPrevSection:function(){return this.get("spine_position")>0},goToNextSection:function(){this.set({spine_position:this.get("spine_position")+1})},goToPrevSection:function(){this.set({spine_position:this.get("spine_position")-1})},goToHref:function(a){var b=this.get("spine"),c=this.get("manifest").find(function(b){var c=b.get("href").match(/[\.\/]*(.*)/);if(a.indexOf(c[c.length-1],a.length-c[c.length-1].length)!==-1)return b});if(!c)return null;for(var c=c.get("id"),d=
0;d<b.length;++d)if(b[d].idref===c){this.set({spine_position:d});break}},getResolvedSpine:function(){for(var a=this.get("spine").length,b=[],c=0;c<a;c++)b.push(this.getManifestItem(c));return b},getTocItem:function(){var a=this.get("manifest"),b=this.get("metadata").ncx,c=a.find(function(a){return a.get("properties")==="nav"});return c?c:b&&b.length>0?a.find(function(a){return a.get("id")===b}):null}});
