if(typeof Readium.FileSystemApi==="undefined")throw"ExtractBook holds Readium::FileSystemApi as a dependency";if(typeof Readium.Utils.MD5==="undefined")throw"Extract holds Readium::Utils::MD5 as a dependency";
Readium.Models.BookExtractorBase=Backbone.Model.extend({MIMETYPE:"mimetype",CONTAINER:"META-INF/container.xml",EPUB3_MIMETYPE:"application/epub+zip",DISPLAY_OPTIONS:"META-INF/com.apple.ibooks.display-options.xml",defaults:{task_size:100,progress:1,extracting:!1,log_message:"Fetching epub file"},clean:function(){this.removeHandlers();this.fsApi&&this.fsApi.rmdir(this.base_dir_name)},parseContainerRoot:function(a){var b=this.get("root_file_path");this.packageDoc=new Readium.Models.ValidatedPackageMetaData({key:this.base_dir_name,
src_url:this.get("src")},{file_path:this.base_dir_name+"/"+b,root_url:this.get("root_url")+"/"+b});this.packageDoc.reset(a);this.trigger("parsed:root_file")},writeFile:function(a,b,c){var d=this,e=this.base_dir_name+"/"+a;a.indexOf(this.DISPLAY_OPTIONS)>=0&&(typeof b==="string"?this.packageDoc.parseIbooksDisplayOptions(b):this.readEntryByShortName(this.DISPLAY_OPTIONS,function(a){d.packageDoc.parseIbooksDisplayOptions(a)}));this.fsApi.writeFile(e,b,c,function(){d.set("error","ERROR: while writing to filesystem")})},
parseMetaInfo:function(a){a=(new window.DOMParser).parseFromString(a,"text/xml").getElementsByTagName("rootfile");a.length!==1?this.set("error","Error processing "+CONTAINER):a[0].hasAttribute("full-path")?this.set("root_file_path",a[0].attributes["full-path"].value):this.set("error","Error: could not find package rootfile")},validateMimetype:function(a){$.trim(a)===this.EPUB3_MIMETYPE?this.trigger("validated:mime"):this.set("error","Invalid mimetype discovered. Progress cancelled.")},removeHandlers:function(){this.off()},
extraction_complete:function(){this.set("extracting",!1)},finish_extraction:function(){var a=this;this.set("log_message","Unpacking process completed successfully!");this.packageDoc.save({},{success:function(){a.trigger("extraction_success")},failure:function(){a.set("failure","ERROR: unknown problem during unpacking process")}})},correctURIs:function(){var a=this.get("root_url"),b=this.get("patch_position"),c=this.get("manifest"),d=this.packageDoc.get("id"),e=this;b>=c.length?(this.off("change:patch_position"),
this.finish_extraction()):(this.set("log_message","monkey patching: "+c[b]),monkeyPatchUrls(a+"/"+c[b],function(){e.incPatchPos()},function(){e.set("failure","ERROR: unknown problem during unpacking process")},d))},incPatchPos:function(){var a=this.get("patch_position")||0;a+=1;this.set("patch_position",a)}});
Readium.Models.ZipBookExtractor=Readium.Models.BookExtractorBase.extend({initialize:function(){var a=this.get("url");if(a)this.base_dir_name=Readium.Utils.MD5(a+(new Date).toString()),this.set("src",this.get("src_filename"));else throw"A URL to a zip file must be specified";},extractEntryByName:function(a,b){for(var c=!1,d=0;d<this.zip.entries.length;d++)if(this.zip.entries[d].name===a){c=!0;this.zip.entries[d].extract(b);break}if(!c)throw"asked to extract non-existent zip-entry: "+a;},extractContainerRoot:function(){var a=
this,b=this.get("root_file_path");try{this.extractEntryByName(b,function(b,c){a.parseContainerRoot(c)})}catch(c){this.set("error",c)}},extractMetaInfo:function(){var a=this;try{this.extractEntryByName(this.CONTAINER,function(b,d){a.parseMetaInfo(d)})}catch(b){this.set("error",b)}},extractMimetype:function(){var a=this;this.set("log_message","Verifying mimetype");try{this.extractEntryByName(this.MIMETYPE,function(b,d){a.validateMimetype(d)})}catch(b){this.set("error",b)}},validateZip:function(){var a=
this.zip.entryNames;this.set("log_message","Validating zip file");a.indexOf(this.MIMETYPE)>=0&&a.indexOf(this.CONTAINER)>=0?this.trigger("validated:zip"):this.set("error","File does not appear to be a valid EPUB. Progress cancelled.")},extractBook:function(){var a;a=this.zip;var b=this.get("zip_position"),c=this;b===a.entries.length?(this.set("log_message","All files unzipped successfully!"),this.set("patch_position",0)):(a=a.entries[b],a.name.substr(-1)==="/"?c.set("zip_position",b+1):(this.set("log_message",
"extracting: "+a.name),a.extract(function(a,e){c.writeFile(a.name,e,function(){c.set("zip_position",b+1)})})))},beginUnpacking:function(){for(var a=[],b,c=0;c<this.zip.entries.length;c++)b=this.zip.entries[c],b.name.substr(-1)!=="/"&&a.push(b.name);this.set("manifest",a);this.set("zip_position",0)},extract:function(){this.on("initialized:zip",this.validateZip,this);this.on("validated:zip",this.extractMimetype,this);this.on("validated:mime",this.extractMetaInfo,this);this.on("change:root_file_path",
this.extractContainerRoot,this);this.on("parsed:root_file",this.beginUnpacking,this);this.on("change:zip_position",this.extractBook,this);this.on("change:patch_position",this.correctURIs,this);this.on("change:failure",this.clean,this);this.on("change:failure",this.removeHandlers,this);this.on("change:task_size",this.update_progress,this);this.on("change:zip_position",this.update_progress,this);this.on("change:patch_position",this.update_progress,this);this.on("extraction_success",this.extraction_complete,
this);this.set("extracting",!0);var a=this;Readium.FileSystemApi(function(b){a.fsApi=b;a.initializeZip()})},update_progress:function(){var a=this.get("zip_position")||0,b=this.get("patch_position")||0;this.set("progress",Math.floor((a+b+3)*100/this.get("task_size")))},initializeZip:function(){var a=this;this.fsApi.getFileSystem().root.getDirectory(this.base_dir_name,{create:!0},function(b){a.set("root_url",b.toURL());a.zip=new ZipFile(a.get("url"),function(){a.set("task_size",a.zip.entries.length*
2+3);a.trigger("initialized:zip")},0)},function(){console.log("In beginUnpacking error handler. Does the root dir already exist?")})}});
Readium.Models.UnpackedBookExtractor=Readium.Models.BookExtractorBase.extend({initialize:function(){var a=this.get("dir_picker"),b=[],c;this.fNameStartInd=a.files[0].webkitRelativePath.indexOf("/")+1;this.base_dir_name=Readium.Utils.MD5("Banana"+(new Date).toString());this.fileList=a.files;for(a=0;c=this.fileList[a];++a)c=c.webkitRelativePath,c.substr(-2)!=="/."&&b.push(this.getShortName(c));this.set("src","Local Directory: "+this.fileList[0].webkitRelativePath.substring(0,this.fNameStartInd));this.set("task_size",
b.length*2+3);this.set("manifest",b)},getShortName:function(a){return a.substr(this.fNameStartInd)},update_progress:function(){var a=this.get("write_position")||0,b=this.get("patch_position")||0;this.set("progress",3+a+b)},extract:function(){this.on("validated:dir",this.readMime,this);this.on("validated:mime",this.readMetaInfo,this);this.on("change:root_file_path",this.readContainerRoot,this);this.on("parsed:root_file",this.beginWriting,this);this.on("change:write_position",this.writeEntry,this);
this.on("change:patch_position",this.correctURIs,this);this.on("change:failure",this.clean,this);this.on("change:failure",this.removeHandlers,this);this.on("change:task_size",this.update_progress,this);this.on("change:write_position",this.update_progress,this);this.on("change:patch_position",this.update_progress,this);this.on("extraction_success",this.extraction_complete,this);this.set("extracting",!0);var a=this;Readium.FileSystemApi(function(b){a.fsApi=b;b.getFileSystem().root.getDirectory(a.base_dir_name,
{create:!0},function(b){a.set("root_url",b.toURL());a.validateDir()})})},validateDir:function(){var a=this.get("manifest");a.indexOf(this.MIMETYPE)>=0&&a.indexOf(this.CONTAINER)>=0?this.trigger("validated:dir"):this.set("error","the directory you selected was not valid")},readMime:function(){var a=this;this.set("log_message","Verifying mimetype");try{this.readEntryByShortName(this.MIMETYPE,function(b){a.validateMimetype(b)})}catch(b){this.set("error",b)}},readMetaInfo:function(){var a=this;try{this.readEntryByShortName(this.CONTAINER,
function(b){a.parseMetaInfo(b)})}catch(b){this.set("error",b)}},readContainerRoot:function(){var a=this,b=this.get("root_file_path");try{this.readEntryByShortName(b,function(b){a.parseContainerRoot(b)})}catch(c){this.set("error",c)}},beginWriting:function(){this.set("write_position",0)},writeEntry:function(){var a=this,b=this.get("write_position");if(b===this.fileList.length)this.set("patch_position",0);else{var c=this.fileList[b],d=this.getShortName(c.webkitRelativePath);this.set("log_message","writing: "+
d);d.substr(-2)==="/."?this.set("write_position",b+1):this.writeFile(d,c,function(){a.set("write_position",b+1)})}},readEntryByShortName:function(a,b){for(var c=!1,d=this.get("dir_picker").files,e=0;e<d.length;e++)if(this.getShortName(d[e].webkitRelativePath)===a){var c=!0,f=new FileReader;f.onload=function(a){b(a.target.result)};f.readAsText(d[e]);break}if(!c)throw"asked to read non-existent file: "+a;}});
