Readium.Models.Ebook=Backbone.Model.extend({initialize:function(){var a=this;this.paginator=new Readium.Models.Paginator({book:this});this.packageDocument=new Readium.Models.PackageDocument({book:a},{file_path:this.get("package_doc_path")});this.packageDocument.fetch({success:function(){var b=a.restorePosition();a.set("spine_position",b);b=a.paginator.renderSpineItems(!1);a.set("rendered_spine_items",b);a.set("has_toc",!!a.packageDocument.getTocItem())}});this.on("change:num_pages",this.adjustCurrentPage,
this);this.on("change:spine_position",this.savePosition,this);this.on("change:spine_position",this.setMetaSize,this)},save:function(a,b){var c={success:function(){}};_.extend(c,b);var d=this;this.set("updated_at",new Date);Lawnchair(function(){this.save(d.toJSON(),c.success)})},defaults:{font_size:10,current_page:[1],num_pages:0,two_up:!1,full_screen:!1,toolbar_visible:!0,toc_visible:!1,can_two_up:!0,rendered_spine_items:[],current_theme:"default-theme",current_margin:3},toJSON:function(){return{apple_fixed:this.get("apple_fixed"),
author:this.get("author"),cover_href:this.get("cover_href"),created_at:this.get("created_at"),current_theme:this.get("current_theme"),description:this.get("description"),epub_version:this.get("epub_version"),fixed_layout:this.get("fixed_layout"),id:this.get("id"),key:this.get("key"),language:this.get("language"),layout:this.get("layout"),modified_date:this.get("modified_date"),ncx:this.get("ncx"),open_to_spread:this.get("open_to_spread"),orientation:this.get("orientation"),package_doc_path:this.get("package_doc_path"),
page_prog_dir:this.get("page_prog_dir"),paginate_backwards:this.get("paginate_backwards"),pubdate:this.get("pubdate"),publisher:this.get("publisher"),rights:this.get("rights"),spread:this.get("spread"),src_url:this.get("src_url"),title:this.get("title"),updated_at:this.get("updated_at"),current_theme:this.get("current_theme"),current_margin:this.get("current_margin"),font_size:this.get("font_size"),two_up:this.get("two_up")}},toggleTwoUp:function(){if(this.get("can_two_up")){debugger;var a=this.get("two_up"),
b=this.get("current_page"),c=[];a?c[0]=b[0]===0?1:b[0]:this.getCurrentSection().isFixedLayout()?b[0]%2===0?(c[0]=b[0],c[1]=b[0]+1):(c[0]=b[0]-1,c[1]=b[0]):b[0]%2===1?(c[0]=b[0],c[1]=b[0]+1):(c[0]=b[0]-1,c[1]=b[0]);this.set({two_up:!a,current_page:c})}},toggleFullScreen:function(){this.set({full_screen:!this.get("full_screen")})},increaseFont:function(){this.set({font_size:this.get("font_size")+1})},decreaseFont:function(){this.set({font_size:this.get("font_size")-1})},toggleToc:function(){this.set("toc_visible",
!this.get("toc_visible"))},prevPage:function(){var a=this.get("current_page"),b=a[0]-1;a[0]<=1?this.goToPrevSection():this.get("two_up")?(this.set("current_page",[b-1,b]),this.get("rendered_spine_items").length>1&&(a=this.get("rendered_spine_items")[b>1?b-2:0],this.set("spine_position",a))):(this.set("current_page",[b]),this.get("rendered_spine_items").length>1&&(a=this.get("rendered_spine_items")[b-1],this.set("spine_position",a)))},nextPage:function(){var a=this.get("current_page"),b=a[a.length-
1]+1;a[a.length-1]>=this.get("num_pages")?this.goToNextSection():(this.get("two_up")?this.set("current_page",[b,b+1]):this.set("current_page",[b]),this.get("rendered_spine_items").length>1&&(a=this.get("rendered_spine_items")[b-1],this.set("spine_position",a)))},goToLastPage:function(){this.goToPage(this.get("num_pages"))},goToPage:function(a){this.get("two_up")?this.getCurrentSection().isFixedLayout()?a%2===0?this.set("current_page",[a,a+1]):this.set("current_page",[a-1,a]):a%2===1?this.set("current_page",
[a,a+1]):this.set("current_page",[a-1,a]):this.set("current_page",[a])},restorePosition:function(){var a=Readium.Utils.getCookie(this.get("key"));return parseInt(a,10)||0},savePosition:function(){Readium.Utils.setCookie(this.get("key"),this.get("spine_position"),365)},resolvePath:function(a){return this.packageDocument.resolvePath(a)},adjustCurrentPage:function(){var a=this.get("current_page"),b=this.get("num_pages");this.get("two_up");a[a.length-1]>b&&this.goToLastPage()},goToNextSection:function(){this.hasNextSection()&&
this.setSpinePos(this.get("spine_position")+1)},goToPrevSection:function(){this.hasPrevSection()&&this.setSpinePosBackwards(this.get("spine_position")-1)},hasNextSection:function(){return this.get("spine_position")<this.packageDocument.spineLength()-1},hasPrevSection:function(){return this.get("spine_position")>0},setSpinePos:function(a){if(!(a<0||a>=this.packageDocument.spineLength())){var b=this.get("rendered_spine_items");this.set("spine_position",a);b.indexOf(a)>=0?b.length>1&&this.goToPage(b.indexOf(a)+
1):this.set("rendered_spine_items",this.paginator.renderSpineItems(!1))}},setSpinePosBackwards:function(a){a<0||a>=this.packageDocument.spineLength()||(this.set("spine_position",a),this.get("rendered_spine_items").indexOf(a)>=0||this.set("rendered_spine_items",this.paginator.renderSpineItems(!0)))},goToHref:function(a){a=a.match(/([^#]*)(?:#(.*))?/);a[1]&&this.setSpinePos(this.packageDocument.spineIndexFromHref(a[1]));a[2]&&this.set({hash_fragment:a[2]})},changPageNumber:function(a){var b=this.get("current_page"),
c=[],d=a-b[b.length-1];d>0&&(d=0);for(var e=0;e<b.length;e++)c[e]=b[e]+d;this.set({num_pages:a,current_page:c})},getToc:function(){var a=this.packageDocument.getTocItem();return a?Readium.Models.Toc.getToc(a,{file_path:this.resolvePath(a.get("href")),book:this}):null},setMetaSize:function(){this.meta_section&&this.meta_section.off("change:meta_height",this.setMetaSize);this.meta_section=this.getCurrentSection();this.meta_section.get("meta_height")&&this.set("meta_size",{width:this.meta_section.get("meta_width"),
height:this.meta_section.get("meta_height")});this.meta_section.on("change:meta_height",this.setMetaSize,this)},spinePositionChangedHandler:function(){var a=this,b=this.getCurrentSection().get("href"),c=this.packageDocument.resolveUri(b),b=this.resolvePath(b);this.set("current_section_url",c);Readium.FileSystemApi(function(c){c.readTextFile(b,function(b){a.set({current_content:b})},function(){console.log("Failed to load file: "+b)})});this.savePosition()},getCurrentSection:function(a){a||(a=0);return this.packageDocument.getSpineItem(this.get("spine_position")+
a)},playMo:function(a){var b=this.getCurrentSection().getMediaOverlay();if(b){this.set("mo_playing",b);var c=this;b.on("change:current_text_document_url",function(){c.goToHref(b.get("current_text_document_url"))});b.on("change:current_text_element_id",function(){var a=b.get("current_text_element_id");c.set("hash_fragment",a);c.set("current_mo_frag",a)});b.on("change:is_document_done",function(){c.pauseMo();c.hasNextSection()&&(c.goToNextSection(),c.playMo(!0))});b.get("has_started_playback")&&a==
!1?b.resume():b.startPlayback(null)}else alert("Sorry, the current EPUB does not contain a media overlay for this content")},pauseMo:function(){var a=this.get("mo_playing");a&&(a.off(),a.pause(),this.set("mo_playing",null))},isFixedLayout:function(){return this.get("fixed_layout")||this.get("apple_fixed")}});
