Readium.Views.ReflowablePaginationView=Readium.Views.PaginationViewBase.extend({initialize:function(){Readium.Views.PaginationViewBase.prototype.initialize.call(this);this.page_template=_.template($("#reflowing-template").html());this.stashModernizrPrefixedProps();this.offset_dir=this.model.get("page_prog_dir")==="rtl"?"right":"left";this.model.on("change:current_page",this.pageChangeHandler,this);this.model.on("change:toc_visible",this.windowSizeChangeHandler,this);this.model.on("repagination_event",
this.windowSizeChangeHandler,this);this.model.on("change:current_theme",this.injectTheme,this);this.model.on("change:two_up",this.setUpMode,this);this.model.on("change:two_up",this.adjustIframeColumns,this);this.model.on("change:current_margin",this.marginCallback,this);this.model.on("change:mo_playing",this.renderMoPlaying,this);this.model.on("change:current_mo_frag",this.renderMoFragHighlight,this)},stashModernizrPrefixedProps:function(){var a=function(a){return a.replace(/([A-Z])/g,function(a,
b){return"-"+b.toLowerCase()}).replace(/^ms-/,"-ms-")};this.columAxis=Modernizr.prefixed("columnAxis")||"columnAxis";this.columGap=Modernizr.prefixed("columnGap")||"columnGap";this.columWidth=Modernizr.prefixed("columnWidth")||"columnWidth";this.cssColumAxis=a(this.columAxis);this.cssColumGap=a(this.columGap);this.cssColumWidth=a(this.columWidth)},destruct:function(){this.model.off("change:current_page",this.pageChangeHandler);this.model.off("change:toc_visible",this.windowSizeChangeHandler);this.model.off("repagination_event",
this.windowSizeChangeHandler);this.model.off("change:current_theme",this.windowSizeChangeHandler);this.model.off("change:two_up",this.setUpMode);this.model.off("change:two_up",this.adjustIframeColumns);this.model.off("change:current_margin",this.marginCallback);this.model.off("change:mo_playing",this.renderMoPlaying);this.model.off("change:current_mo_frag",this.renderMoFragHighlight);Readium.Views.PaginationViewBase.prototype.destruct.call(this)},render:function(a){var b=this,c=this.model.getCurrentSection().toJSON();
this.setUpMode();this.$("#container").html(this.page_template(c));this.setFrameWidth();this.$("#readium-flowing-content").on("load",function(c){b.adjustIframeColumns();b.iframeLoadCallback(c);b.setFontSize();b.injectTheme();b.setNumPages();a?b.model.goToLastPage():b.model.goToPage(1)});return this},getBodyColumnCss:function(){var a={};a[this.cssColumAxis]="horizontal";a[this.cssColumGap]=this.gap_width.toString()+"px";a[this.cssColumWidth]=this.page_width.toString()+"px";a.padding="0px";a.margin=
"0px";a.position="absolute";a.width=this.page_width.toString()+"px";a.height=this.frame_height.toString()+"px";return a},adjustIframeColumns:function(){var a=this.$("#readium-flowing-content");this.frame_width=parseInt(a.width(),10);this.frame_height=parseInt(a.height(),10);this.gap_width=Math.floor(this.frame_width/7);this.page_width=this.model.get("two_up")?Math.floor((this.frame_width-this.gap_width)/2):this.frame_width;$(this.getBody()).css(this.getBodyColumnCss());this.setNumPages();this.goToPage(this.model.get("current_page")[0]||
1)},getBody:function(){return this.$("#readium-flowing-content").contents()[0].documentElement},hideContent:function(){$("#flowing-wrapper").css("opacity","0")},showContent:function(){$("#flowing-wrapper").css("opacity","1")},calcPageOffset:function(a){return(a-1)*(this.page_width+this.gap_width)},setFrameWidth:function(){var a,b=this.model.get("current_margin");b===1?this.model.get("two_up")?a="90%":a="80%":b===2?this.model.get("two_up")?a="80%":a="70%":b===3?this.model.get("two_up")?a="70%":a="60%":
b===4?this.model.get("two_up")?a="60%":a="50%":this.model.get("two_up")?a="50%":a="40%";this.$("#readium-flowing-content").attr("width",a)},calcNumPages:function(){var a,b,c;a=this.getBody();b=a.style[this.offset_dir];a.style[this.offset_dir]="0px";c=this.getBody().scrollWidth;a.style[this.offset_dir]=b;a=Math.floor((c+this.gap_width)/(this.gap_width+this.page_width));a%2===0&&this.model.get("two_up");return a},pageChangeHandler:function(){var a=this;this.hideContent();setTimeout(function(){a.goToPage(a.model.get("current_page")[0])},
150)},goToPage:function(a){a=this.calcPageOffset(a).toString()+"px";$(this.getBody()).css(this.offset_dir,"-"+a);this.showContent()},goToHashFragment:function(){var a=this.model.get("hash_fragment");if(a&&(a=$("#"+a,this.getBody())[0])){for(;a.children.length>0;)a=a.children[0];a=this.getElemPageNumber(a);a>0&&this.model.goToPage(a)}},getElemPageNumber:function(a){a=a.getClientRects();if(!a||a.length<1)return-1;a=a[0][this.offset_dir];a-=parseInt(this.getBody().style[this.offset_dir],10);return Math.ceil(a/
(this.page_width+this.gap_width))},windowSizeChangeHandler:function(){this.adjustIframeColumns()},setFontSize:function(){var a=this.model.get("font_size")/10;$(this.getBody()).css("font-size",a+"em");this.setNumPages()},marginCallback:function(){this.setFrameWidth();this.adjustIframeColumns()},themes:{"default-theme":{"background-color":"white",color:"black","mo-color":"#777"},"vancouver-theme":{"background-color":"#DDD",color:"#576b96","mo-color":"#777"},"ballard-theme":{"background-color":"#576b96",
color:"#DDD","mo-color":"#888"},"parchment-theme":{"background-color":"#f7f1cf",color:"#774c27","mo-color":"#eebb22"},"night-theme":{"background-color":"black",color:"white","mo-color":"#666"}},injectTheme:function(){var a=this.model.get("current_theme");a==="default"&&(a="default-theme");$(this.getBody()).css({color:this.themes[a].color,"background-color":this.themes[a]["background-color"]});this.renderMoPlaying()},setNumPages:function(){var a=this.calcNumPages();console.log("num pages is: "+a);
this.model.set("num_pages",a)},renderMoPlaying:function(){var a=this.model.get("current_theme");a==="default"&&(a="default-theme");this.model.get("mo_playing")?$(this.getBody()).css("color",this.themes[a]["mo-color"]):($(this.getBody()).css("color",this.themes[a].color),$(".current-mo-content",this.getBody()).toggleClass("current-mo-content",!1).css("color",""))},renderMoFragHighlight:function(){var a=this.model.get("current_theme");a==="default"&&(a="default-theme");$(".current-mo-content",this.getBody()).toggleClass("current-mo-content",
!1).css("color","");var b=this.model.get("current_mo_frag");b&&$("#"+b,this.getBody()).toggleClass("current-mo-content",!0).css("color",this.themes[a].color)}});
