Readium.Models.LibraryItem=Backbone.Model.extend({idAttribute:"key",getViewBookUrl:function(){return"/views/viewer.html?book="+this.get("key")},openInReader:function(){window.location=this.getViewBookUrl()},destroy:function(){var a=this.get("key");Lawnchair(function(){var b=this;this.get(a,function(c){c&&Readium.FileSystemApi(function(d){d.rmdir(c.key);b.remove(a)})})})}});Readium.Collections.LibraryItems=Backbone.Collection.extend({model:Readium.Models.LibraryItem});
Readium.Views.LibraryItemView=Backbone.View.extend({tagName:"div",className:"book-item clearfix",initialize:function(){this.template=_.template($("#library-item-template").html())},render:function(){var a=this.template({data:this.model.toJSON()});$(this.el).html(a);return this},events:{"click .delete":function(a){a.preventDefault();var b="#details-modal-"+this.model.get("key"),a="Are you sure you want to permanently delete ";a+=this.model.get("title");a+="?";confirm(a)&&($(b).modal("hide"),this.model.destroy(),
this.remove())},"click .read":function(){this.model.openInReader()}}});
Readium.Views.LibraryItemsView=Backbone.View.extend({tagName:"div",id:"library-items-container",className:"row-view clearfix",initialize:function(){this.template=_.template($("#library-items-template").html());this.collection.bind("reset",this.render,this);this.collection.bind("add",this.addOne,this)},render:function(){var a=this.collection,b=this.template({}),c=this.$el;c.html(b);this.$("#empty-message").toggle(a.isEmpty());a.each(function(b){b=new Readium.Views.LibraryItemView({model:b,collection:a,
id:b.get("id")});c.append(b.render().el)});this.restoreViewType();$("#library-books-list").html(this.el);return this},restoreViewType:function(){Readium.Utils.getCookie("lib_view")==="block"&&this.$el.addClass("block-view").removeClass("row-view")},addOne:function(a){a=new Readium.Views.LibraryItemView({model:a,collection:this.collection,id:a.get("id")});this.$("#empty-message").toggle(!1);$(this.el).append(a.render().el)},events:{}});
Readium.Views.ExtractItemView=Backbone.View.extend({el:"#progress-container",initialize:function(){this.template=_.template($("#extracting-item-template").html());this.model.bind("change",this.render,this);this.model.bind("change:error",this.extractionFailed,this)},render:function(){var a=$(this.el);this.model.get("extracting")?(a.html(this.template(this.model.toJSON())),a.show("slow")):a.hide("slow");return this},extractionFailed:function(){alert(this.model.get("error"));this.model.set("extracting",
!1)}});
Readium.Views.ReadiumOptionsView=Backbone.View.extend({el:"#readium-options-modal",initialize:function(){this.model.on("change",this.render,this);this.render()},render:function(){var a=this.model;this.$("#paginate_everything").prop("checked",a.get("paginate_everything"));this.$("#verbose_unpacking").prop("checked",a.get("verbose_unpacking"));this.$("#hijack_epub_urls").prop("checked",a.get("hijack_epub_urls"))},events:{"change #verbose_unpacking":"updateSettings","change #hijack_epub_urls":"updateSettings","change #paginate_everything":"updateSettings",
"click #save-settings-btn":"save"},updateSettings:function(){var a=this.$("#hijack_epub_urls").prop("checked"),b=this.$("#verbose_unpacking").prop("checked"),c=this.$("#paginate_everything").prop("checked");this.model.set({verbose_unpacking:b,hijack_epub_urls:a,paginate_everything:c})},save:function(){this.model.save();this.$el.modal("hide")}});
Readium.Views.FilePickerView=Backbone.View.extend({el:"#add-book-modal",events:{"change #files":"handleFileSelect","change #dir_input":"handleDirSelect","click #url-button":"handleUrl"},show:function(){this.$el.modal("show")},hide:function(){this.$el.modal("hide")},resetForm:function(){},handleUrl:function(){var a=document.getElementById("book-url");a.value===null||a.value.length<1?alert("invalid url, cannot process"):(a=a.value,this.beginExtraction(new Readium.Models.ZipBookExtractor({url:a,src_filename:a})))},
handleFileSelect:function(a){var a=a.target.files,b=window.webkitURL.createObjectURL(a[0]);this.beginExtraction(new Readium.Models.ZipBookExtractor({url:b,src_filename:a[0].name}))},handleDirSelect:function(a){this.beginExtraction(new Readium.Models.UnpackedBookExtractor({dir_picker:a.target}))},beginExtraction:function(a){var b=this;window._extract_view=new Readium.Views.ExtractItemView({model:a});a.on("extraction_success",function(){var c=a.packageDoc.toJSON();b.collection.add(new Readium.Models.LibraryItem(c));
setTimeout(function(){chrome.tabs.create({url:"/views/viewer.html?book="+c.key})},800)});a.extract();this.resetForm();this.hide()}});
