(function(){function c(b,a,k){if(b===a)return b!==0||1/b==1/a;if(b==null||a==null)return b===a;if(b._chain)b=b._wrapped;if(a._chain)a=a._wrapped;if(b.isEqual&&f.isFunction(b.isEqual))return b.isEqual(a);if(a.isEqual&&f.isFunction(a.isEqual))return a.isEqual(b);var d=j.call(b);if(d!=j.call(a))return!1;switch(d){case "[object String]":return b==String(a);case "[object Number]":return b!=+b?a!=+a:b==0?1/b==1/a:b==+a;case "[object Date]":case "[object Boolean]":return+b==+a;case "[object RegExp]":return b.source==
a.source&&b.global==a.global&&b.multiline==a.multiline&&b.ignoreCase==a.ignoreCase}if(typeof b!="object"||typeof a!="object")return!1;for(var g=k.length;g--;)if(k[g]==b)return!0;k.push(b);var g=0,e=!0;if(d=="[object Array]"){if(g=b.length,e=g==a.length)for(;g--;)if(!(e=g in b==g in a&&c(b[g],a[g],k)))break}else{if("constructor"in b!="constructor"in a||b.constructor!=a.constructor)return!1;for(var h in b)if(f.has(b,h)&&(g++,!(e=f.has(a,h)&&c(b[h],a[h],k))))break;if(e){for(h in a)if(f.has(a,h)&&!g--)break;
e=!g}}k.pop();return e}var e=this,d=e._,b={},a=Array.prototype,g=Object.prototype,h=a.slice,l=a.unshift,j=g.toString,o=g.hasOwnProperty,p=a.forEach,t=a.map,n=a.reduce,v=a.reduceRight,x=a.filter,q=a.every,r=a.some,m=a.indexOf,s=a.lastIndexOf,g=Array.isArray,y=Object.keys,k=Function.prototype.bind,f=function(b){return new w(b)};if(typeof exports!=="undefined"){if(typeof module!=="undefined"&&module.exports)exports=module.exports=f;exports._=f}else e._=f;f.VERSION="1.3.1";var u=f.each=f.forEach=function(a,
k,d){if(a!=null)if(p&&a.forEach===p)a.forEach(k,d);else if(a.length===+a.length)for(var c=0,g=a.length;c<g;c++){if(c in a&&k.call(d,a[c],c,a)===b)break}else for(c in a)if(f.has(a,c)&&k.call(d,a[c],c,a)===b)break};f.map=f.collect=function(a,b,f){var k=[];if(a==null)return k;if(t&&a.map===t)return a.map(b,f);u(a,function(a,d,c){k[k.length]=b.call(f,a,d,c)});if(a.length===+a.length)k.length=a.length;return k};f.reduce=f.foldl=f.inject=function(a,b,k,d){var c=arguments.length>2;a==null&&(a=[]);if(n&&
a.reduce===n)return d&&(b=f.bind(b,d)),c?a.reduce(b,k):a.reduce(b);u(a,function(a,f,E){c?k=b.call(d,k,a,f,E):(k=a,c=!0)});if(!c)throw new TypeError("Reduce of empty array with no initial value");return k};f.reduceRight=f.foldr=function(a,b,k,d){var c=arguments.length>2;a==null&&(a=[]);if(v&&a.reduceRight===v)return d&&(b=f.bind(b,d)),c?a.reduceRight(b,k):a.reduceRight(b);var g=f.toArray(a).reverse();d&&!c&&(b=f.bind(b,d));return c?f.reduce(g,b,k,d):f.reduce(g,b)};f.find=f.detect=function(a,b,f){var k;
C(a,function(a,d,c){if(b.call(f,a,d,c))return k=a,!0});return k};f.filter=f.select=function(a,b,f){var k=[];if(a==null)return k;if(x&&a.filter===x)return a.filter(b,f);u(a,function(a,d,c){b.call(f,a,d,c)&&(k[k.length]=a)});return k};f.reject=function(a,b,f){var k=[];if(a==null)return k;u(a,function(a,d,c){b.call(f,a,d,c)||(k[k.length]=a)});return k};f.every=f.all=function(a,f,k){var d=!0;if(a==null)return d;if(q&&a.every===q)return a.every(f,k);u(a,function(a,c,g){if(!(d=d&&f.call(k,a,c,g)))return b});
return d};var C=f.some=f.any=function(a,k,d){k||(k=f.identity);var c=!1;if(a==null)return c;if(r&&a.some===r)return a.some(k,d);u(a,function(a,f,g){if(c||(c=k.call(d,a,f,g)))return b});return!!c};f.include=f.contains=function(a,b){var f;return a==null?!1:m&&a.indexOf===m?a.indexOf(b)!=-1:f=C(a,function(a){return a===b})};f.invoke=function(a,b){var k=h.call(arguments,2);return f.map(a,function(a){return(f.isFunction(b)?b||a:a[b]).apply(a,k)})};f.pluck=function(a,b){return f.map(a,function(a){return a[b]})};
f.max=function(a,b,k){if(!b&&f.isArray(a))return Math.max.apply(Math,a);if(!b&&f.isEmpty(a))return-Infinity;var d={computed:-Infinity};u(a,function(a,f,c){f=b?b.call(k,a,f,c):a;f>=d.computed&&(d={value:a,computed:f})});return d.value};f.min=function(a,b,k){if(!b&&f.isArray(a))return Math.min.apply(Math,a);if(!b&&f.isEmpty(a))return Infinity;var d={computed:Infinity};u(a,function(a,f,c){f=b?b.call(k,a,f,c):a;f<d.computed&&(d={value:a,computed:f})});return d.value};f.shuffle=function(a){var b=[],f;
u(a,function(a,k){k==0?b[0]=a:(f=Math.floor(Math.random()*(k+1)),b[k]=b[f],b[f]=a)});return b};f.sortBy=function(a,b,k){return f.pluck(f.map(a,function(a,f,d){return{value:a,criteria:b.call(k,a,f,d)}}).sort(function(a,b){var f=a.criteria,k=b.criteria;return f<k?-1:f>k?1:0}),"value")};f.groupBy=function(a,b){var k={},d=f.isFunction(b)?b:function(a){return a[b]};u(a,function(a,b){var f=d(a,b);(k[f]||(k[f]=[])).push(a)});return k};f.sortedIndex=function(a,b,k){k||(k=f.identity);for(var d=0,c=a.length;d<
c;){var g=d+c>>1;k(a[g])<k(b)?d=g+1:c=g}return d};f.toArray=function(a){return!a?[]:a.toArray?a.toArray():f.isArray(a)?h.call(a):f.isArguments(a)?h.call(a):f.values(a)};f.size=function(a){return f.toArray(a).length};f.first=f.head=function(a,b,f){return b!=null&&!f?h.call(a,0,b):a[0]};f.initial=function(a,b,f){return h.call(a,0,a.length-(b==null||f?1:b))};f.last=function(a,b,f){return b!=null&&!f?h.call(a,Math.max(a.length-b,0)):a[a.length-1]};f.rest=f.tail=function(a,b,f){return h.call(a,b==null||
f?1:b)};f.compact=function(a){return f.filter(a,function(a){return!!a})};f.flatten=function(a,b){return f.reduce(a,function(a,k){if(f.isArray(k))return a.concat(b?k:f.flatten(k));a[a.length]=k;return a},[])};f.without=function(a){return f.difference(a,h.call(arguments,1))};f.uniq=f.unique=function(a,b,k){var k=k?f.map(a,k):a,d=[];f.reduce(k,function(k,c,g){if(0==g||(b===!0?f.last(k)!=c:!f.include(k,c)))k[k.length]=c,d[d.length]=a[g];return k},[]);return d};f.union=function(){return f.uniq(f.flatten(arguments,
!0))};f.intersection=f.intersect=function(a){var b=h.call(arguments,1);return f.filter(f.uniq(a),function(a){return f.every(b,function(b){return f.indexOf(b,a)>=0})})};f.difference=function(a){var b=f.flatten(h.call(arguments,1));return f.filter(a,function(a){return!f.include(b,a)})};f.zip=function(){for(var a=h.call(arguments),b=f.max(f.pluck(a,"length")),k=Array(b),d=0;d<b;d++)k[d]=f.pluck(a,""+d);return k};f.indexOf=function(a,b,k){if(a==null)return-1;var d;if(k)return k=f.sortedIndex(a,b),a[k]===
b?k:-1;if(m&&a.indexOf===m)return a.indexOf(b);for(k=0,d=a.length;k<d;k++)if(k in a&&a[k]===b)return k;return-1};f.lastIndexOf=function(a,b){if(a==null)return-1;if(s&&a.lastIndexOf===s)return a.lastIndexOf(b);for(var f=a.length;f--;)if(f in a&&a[f]===b)return f;return-1};f.range=function(a,b,f){arguments.length<=1&&(b=a||0,a=0);for(var f=arguments[2]||1,k=Math.max(Math.ceil((b-a)/f),0),d=0,c=Array(k);d<k;)c[d++]=a,a+=f;return c};var D=function(){};f.bind=function(a,b){var d,c;if(a.bind===k&&k)return k.apply(a,
h.call(arguments,1));if(!f.isFunction(a))throw new TypeError;c=h.call(arguments,2);return d=function(){if(!(this instanceof d))return a.apply(b,c.concat(h.call(arguments)));D.prototype=a.prototype;var f=new D,k=a.apply(f,c.concat(h.call(arguments)));return Object(k)===k?k:f}};f.bindAll=function(a){var b=h.call(arguments,1);b.length==0&&(b=f.functions(a));u(b,function(b){a[b]=f.bind(a[b],a)});return a};f.memoize=function(a,b){var k={};b||(b=f.identity);return function(){var d=b.apply(this,arguments);
return f.has(k,d)?k[d]:k[d]=a.apply(this,arguments)}};f.delay=function(a,b){var f=h.call(arguments,2);return setTimeout(function(){return a.apply(a,f)},b)};f.defer=function(a){return f.delay.apply(f,[a,1].concat(h.call(arguments,1)))};f.throttle=function(a,b){var k,d,c,g,e,h=f.debounce(function(){e=g=!1},b);return function(){k=this;d=arguments;c||(c=setTimeout(function(){c=null;e&&a.apply(k,d);h()},b));g?e=!0:a.apply(k,d);h();g=!0}};f.debounce=function(a,b){var f;return function(){var k=this,d=arguments;
clearTimeout(f);f=setTimeout(function(){f=null;a.apply(k,d)},b)}};f.once=function(a){var b=!1,f;return function(){if(b)return f;b=!0;return f=a.apply(this,arguments)}};f.wrap=function(a,b){return function(){var f=[a].concat(h.call(arguments,0));return b.apply(this,f)}};f.compose=function(){var a=arguments;return function(){for(var b=arguments,f=a.length-1;f>=0;f--)b=[a[f].apply(this,b)];return b[0]}};f.after=function(a,b){return a<=0?b():function(){if(--a<1)return b.apply(this,arguments)}};f.keys=
y||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var b=[],k;for(k in a)f.has(a,k)&&(b[b.length]=k);return b};f.values=function(a){return f.map(a,f.identity)};f.functions=f.methods=function(a){var b=[],k;for(k in a)f.isFunction(a[k])&&b.push(k);return b.sort()};f.extend=function(a){u(h.call(arguments,1),function(b){for(var f in b)a[f]=b[f]});return a};f.defaults=function(a){u(h.call(arguments,1),function(b){for(var f in b)a[f]==null&&(a[f]=b[f])});return a};f.clone=function(a){return!f.isObject(a)?
a:f.isArray(a)?a.slice():f.extend({},a)};f.tap=function(a,b){b(a);return a};f.isEqual=function(a,b){return c(a,b,[])};f.isEmpty=function(a){if(f.isArray(a)||f.isString(a))return a.length===0;for(var b in a)if(f.has(a,b))return!1;return!0};f.isElement=function(a){return!!(a&&a.nodeType==1)};f.isArray=g||function(a){return j.call(a)=="[object Array]"};f.isObject=function(a){return a===Object(a)};f.isArguments=function(a){return j.call(a)=="[object Arguments]"};if(!f.isArguments(arguments))f.isArguments=
function(a){return!(!a||!f.has(a,"callee"))};f.isFunction=function(a){return j.call(a)=="[object Function]"};f.isString=function(a){return j.call(a)=="[object String]"};f.isNumber=function(a){return j.call(a)=="[object Number]"};f.isNaN=function(a){return a!==a};f.isBoolean=function(a){return a===!0||a===!1||j.call(a)=="[object Boolean]"};f.isDate=function(a){return j.call(a)=="[object Date]"};f.isRegExp=function(a){return j.call(a)=="[object RegExp]"};f.isNull=function(a){return a===null};f.isUndefined=
function(a){return a===void 0};f.has=function(a,b){return o.call(a,b)};f.noConflict=function(){e._=d;return this};f.identity=function(a){return a};f.times=function(a,b,f){for(var k=0;k<a;k++)b.call(f,k)};f.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};f.mixin=function(a){u(f.functions(a),function(b){F(b,f[b]=a[b])})};var G=0;f.uniqueId=function(a){var b=G++;return a?a+b:b};f.templateSettings=
{evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var z=/.^/,A=function(a){return a.replace(/\\\\/g,"\\").replace(/\\'/g,"'")};f.template=function(a,b){var k=f.templateSettings,k="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(k.escape||z,function(a,b){return"',_.escape("+A(b)+"),'"}).replace(k.interpolate||z,function(a,b){return"',"+A(b)+",'"}).replace(k.evaluate||z,function(a,
b){return"');"+A(b).replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');",d=new Function("obj","_",k);return b?d(b,f):function(a){return d.call(this,a,f)}};f.chain=function(a){return f(a).chain()};var w=function(a){this._wrapped=a};f.prototype=w.prototype;var B=function(a,b){return b?f(a).chain():a},F=function(a,b){w.prototype[a]=function(){var a=h.call(arguments);l.call(a,this._wrapped);return B(b.apply(f,a),this._chain)}};
f.mixin(f);u("pop,push,reverse,shift,sort,splice,unshift".split(","),function(b){var f=a[b];w.prototype[b]=function(){var a=this._wrapped;f.apply(a,arguments);var k=a.length;(b=="shift"||b=="splice")&&k===0&&delete a[0];return B(a,this._chain)}});u(["concat","join","slice"],function(b){var f=a[b];w.prototype[b]=function(){return B(f.apply(this._wrapped,arguments),this._chain)}});w.prototype.chain=function(){this._chain=!0;return this};w.prototype.value=function(){return this._wrapped}}).call(this);
(function(){var c=this,e=c.Backbone,d=Array.prototype.slice,b=Array.prototype.splice,a;a="undefined"!==typeof exports?exports:c.Backbone={};a.VERSION="0.9.1";var g=c._;!g&&"undefined"!==typeof require&&(g=require("underscore"));var h=c.jQuery||c.Zepto||c.ender;a.setDomLibrary=function(a){h=a};a.noConflict=function(){c.Backbone=e;return this};a.emulateHTTP=!1;a.emulateJSON=!1;a.Events={on:function(a,b,d){for(var c,a=a.split(/\s+/),g=this._callbacks||(this._callbacks={});c=a.shift();){c=g[c]||(g[c]=
{});var e=c.tail||(c.tail=c.next={});e.callback=b;e.context=d;c.tail=e.next={}}return this},off:function(a,b,d){var c,g,e;if(a){if(g=this._callbacks)for(a=a.split(/\s+/);c=a.shift();)if(e=g[c],delete g[c],b&&e)for(;(e=e.next)&&e.next;)if(!(e.callback===b&&(!d||e.context===d)))this.on(c,e.callback,e.context)}else delete this._callbacks;return this},trigger:function(a){var b,c,g,e;if(!(g=this._callbacks))return this;e=g.all;for((a=a.split(/\s+/)).push(null);b=a.shift();)e&&a.push({next:e.next,tail:e.tail,
event:b}),(c=g[b])&&a.push({next:c.next,tail:c.tail});for(e=d.call(arguments,1);c=a.pop();){b=c.tail;for(g=c.event?[c.event].concat(e):e;(c=c.next)!==b;)c.callback.apply(c.context||this,g)}return this}};a.Events.bind=a.Events.on;a.Events.unbind=a.Events.off;a.Model=function(a,b){var d;a||(a={});b&&b.parse&&(a=this.parse(a));if(d=s(this,"defaults"))a=g.extend({},d,a);b&&b.collection&&(this.collection=b.collection);this.attributes={};this._escapedAttributes={};this.cid=g.uniqueId("c");if(!this.set(a,
{silent:!0}))throw Error("Can't create an invalid model");delete this._changed;this._previousAttributes=g.clone(this.attributes);this.initialize.apply(this,arguments)};g.extend(a.Model.prototype,a.Events,{idAttribute:"id",initialize:function(){},toJSON:function(){return g.clone(this.attributes)},get:function(a){return this.attributes[a]},escape:function(a){var b;if(b=this._escapedAttributes[a])return b;b=this.attributes[a];return this._escapedAttributes[a]=g.escape(null==b?"":""+b)},has:function(a){return null!=
this.attributes[a]},set:function(b,f,d){var c,e;g.isObject(b)||null==b?(c=b,d=f):(c={},c[b]=f);d||(d={});if(!c)return this;c instanceof a.Model&&(c=c.attributes);if(d.unset)for(e in c)c[e]=void 0;if(!this._validate(c,d))return!1;this.idAttribute in c&&(this.id=c[this.idAttribute]);var f=this.attributes,h=this._escapedAttributes,j=this._previousAttributes||{},l=this._setting;this._changed||(this._changed={});this._setting=!0;for(e in c)if(b=c[e],g.isEqual(f[e],b)||delete h[e],d.unset?delete f[e]:f[e]=
b,this._changing&&!g.isEqual(this._changed[e],b)&&(this.trigger("change:"+e,this,b,d),this._moreChanges=!0),delete this._changed[e],!g.isEqual(j[e],b)||g.has(f,e)!=g.has(j,e))this._changed[e]=b;l||(!d.silent&&this.hasChanged()&&this.change(d),this._setting=!1);return this},unset:function(a,b){(b||(b={})).unset=!0;return this.set(a,null,b)},clear:function(a){(a||(a={})).unset=!0;return this.set(g.clone(this.attributes),a)},fetch:function(b){var b=b?g.clone(b):{},f=this,d=b.success;b.success=function(a,
c,g){if(!f.set(f.parse(a,g),b))return!1;d&&d(f,a)};b.error=a.wrapError(b.error,f,b);return(this.sync||a.sync).call(this,"read",this,b)},save:function(b,f,d){var c,e;g.isObject(b)||null==b?(c=b,d=f):(c={},c[b]=f);d=d?g.clone(d):{};d.wait&&(e=g.clone(this.attributes));b=g.extend({},d,{silent:!0});if(c&&!this.set(c,d.wait?b:d))return!1;var h=this,j=d.success;d.success=function(a,b,f){b=h.parse(a,f);d.wait&&(b=g.extend(c||{},b));if(!h.set(b,d))return!1;j?j(h,a):h.trigger("sync",h,a,d)};d.error=a.wrapError(d.error,
h,d);f=this.isNew()?"create":"update";f=(this.sync||a.sync).call(this,f,this,d);d.wait&&this.set(e,b);return f},destroy:function(b){var b=b?g.clone(b):{},f=this,d=b.success,c=function(){f.trigger("destroy",f,f.collection,b)};if(this.isNew())return c();b.success=function(a){b.wait&&c();d?d(f,a):f.trigger("sync",f,a,b)};b.error=a.wrapError(b.error,f,b);var e=(this.sync||a.sync).call(this,"delete",this,b);b.wait||c();return e},url:function(){var a=s(this.collection,"url")||s(this,"urlRoot")||y();return this.isNew()?
a:a+("/"==a.charAt(a.length-1)?"":"/")+encodeURIComponent(this.id)},parse:function(a){return a},clone:function(){return new this.constructor(this.attributes)},isNew:function(){return null==this.id},change:function(a){if(this._changing||!this.hasChanged())return this;this._moreChanges=this._changing=!0;for(var b in this._changed)this.trigger("change:"+b,this,this._changed[b],a);for(;this._moreChanges;)this._moreChanges=!1,this.trigger("change",this,a);this._previousAttributes=g.clone(this.attributes);
delete this._changed;this._changing=!1;return this},hasChanged:function(a){return!arguments.length?!g.isEmpty(this._changed):this._changed&&g.has(this._changed,a)},changedAttributes:function(a){if(!a)return this.hasChanged()?g.clone(this._changed):!1;var b,d=!1,c=this._previousAttributes,e;for(e in a)if(!g.isEqual(c[e],b=a[e]))(d||(d={}))[e]=b;return d},previous:function(a){return!arguments.length||!this._previousAttributes?null:this._previousAttributes[a]},previousAttributes:function(){return g.clone(this._previousAttributes)},
isValid:function(){return!this.validate(this.attributes)},_validate:function(a,b){if(b.silent||!this.validate)return!0;var a=g.extend({},this.attributes,a),d=this.validate(a,b);if(!d)return!0;b&&b.error?b.error(this,d,b):this.trigger("error",this,d,b);return!1}});a.Collection=function(a,b){b||(b={});b.comparator&&(this.comparator=b.comparator);this._reset();this.initialize.apply(this,arguments);a&&this.reset(a,{silent:!0,parse:b.parse})};g.extend(a.Collection.prototype,a.Events,{model:a.Model,initialize:function(){},
toJSON:function(){return this.map(function(a){return a.toJSON()})},add:function(a,d){var c,e,h,j,l,n={},v={};d||(d={});a=g.isArray(a)?a.slice():[a];for(c=0,e=a.length;c<e;c++){if(!(h=a[c]=this._prepareModel(a[c],d)))throw Error("Can't add an invalid model to a collection");if(n[j=h.cid]||this._byCid[j]||null!=(l=h.id)&&(v[l]||this._byId[l]))throw Error("Can't add the same model to a collection twice");n[j]=v[l]=h}for(c=0;c<e;c++)(h=a[c]).on("all",this._onModelEvent,this),this._byCid[h.cid]=h,null!=
h.id&&(this._byId[h.id]=h);this.length+=e;b.apply(this.models,[null!=d.at?d.at:this.models.length,0].concat(a));this.comparator&&this.sort({silent:!0});if(d.silent)return this;for(c=0,e=this.models.length;c<e;c++)if(n[(h=this.models[c]).cid])d.index=c,h.trigger("add",h,this,d);return this},remove:function(a,b){var d,c,e,h;b||(b={});a=g.isArray(a)?a.slice():[a];for(d=0,c=a.length;d<c;d++)if(h=this.getByCid(a[d])||this.get(a[d]))delete this._byId[h.id],delete this._byCid[h.cid],e=this.indexOf(h),this.models.splice(e,
1),this.length--,b.silent||(b.index=e,h.trigger("remove",h,this,b)),this._removeReference(h);return this},get:function(a){return null==a?null:this._byId[null!=a.id?a.id:a]},getByCid:function(a){return a&&this._byCid[a.cid||a]},at:function(a){return this.models[a]},sort:function(a){a||(a={});if(!this.comparator)throw Error("Cannot sort a set without a comparator");var b=g.bind(this.comparator,this);1==this.comparator.length?this.models=this.sortBy(b):this.models.sort(b);a.silent||this.trigger("reset",
this,a);return this},pluck:function(a){return g.map(this.models,function(b){return b.get(a)})},reset:function(a,b){a||(a=[]);b||(b={});for(var d=0,c=this.models.length;d<c;d++)this._removeReference(this.models[d]);this._reset();this.add(a,{silent:!0,parse:b.parse});b.silent||this.trigger("reset",this,b);return this},fetch:function(b){b=b?g.clone(b):{};void 0===b.parse&&(b.parse=!0);var d=this,c=b.success;b.success=function(a,g,e){d[b.add?"add":"reset"](d.parse(a,e),b);c&&c(d,a)};b.error=a.wrapError(b.error,
d,b);return(this.sync||a.sync).call(this,"read",this,b)},create:function(a,b){var d=this,b=b?g.clone(b):{},a=this._prepareModel(a,b);if(!a)return!1;b.wait||d.add(a,b);var c=b.success;b.success=function(e,g){b.wait&&d.add(e,b);c?c(e,g):e.trigger("sync",a,g,b)};a.save(null,b);return a},parse:function(a){return a},chain:function(){return g(this.models).chain()},_reset:function(){this.length=0;this.models=[];this._byId={};this._byCid={}},_prepareModel:function(b,d){b instanceof a.Model?b.collection||
(b.collection=this):(d.collection=this,b=new this.model(b,d),b._validate(b.attributes,d)||(b=!1));return b},_removeReference:function(a){this==a.collection&&delete a.collection;a.off("all",this._onModelEvent,this)},_onModelEvent:function(a,b,d,c){("add"==a||"remove"==a)&&d!=this||("destroy"==a&&this.remove(b,c),b&&a==="change:"+b.idAttribute&&(delete this._byId[b.previous(b.idAttribute)],this._byId[b.id]=b),this.trigger.apply(this,arguments))}});g.each("forEach,each,map,reduce,reduceRight,find,detect,filter,select,reject,every,all,some,any,include,contains,invoke,max,min,sortBy,sortedIndex,toArray,size,first,initial,rest,last,without,indexOf,shuffle,lastIndexOf,isEmpty,groupBy".split(","),
function(b){a.Collection.prototype[b]=function(){return g[b].apply(g,[this.models].concat(g.toArray(arguments)))}});a.Router=function(a){a||(a={});a.routes&&(this.routes=a.routes);this._bindRoutes();this.initialize.apply(this,arguments)};var l=/:\w+/g,j=/\*\w+/g,o=/[-[\]{}()+?.,\\^$|#\s]/g;g.extend(a.Router.prototype,a.Events,{initialize:function(){},route:function(b,d,c){a.history||(a.history=new a.History);g.isRegExp(b)||(b=this._routeToRegExp(b));c||(c=this[d]);a.history.route(b,g.bind(function(e){e=
this._extractParameters(b,e);c&&c.apply(this,e);this.trigger.apply(this,["route:"+d].concat(e));a.history.trigger("route",this,d,e)},this));return this},navigate:function(b,d){a.history.navigate(b,d)},_bindRoutes:function(){if(this.routes){var a=[],b;for(b in this.routes)a.unshift([b,this.routes[b]]);b=0;for(var d=a.length;b<d;b++)this.route(a[b][0],a[b][1],this[a[b][1]])}},_routeToRegExp:function(a){a=a.replace(o,"\\$&").replace(l,"([^/]+)").replace(j,"(.*?)");return RegExp("^"+a+"$")},_extractParameters:function(a,
b){return a.exec(b).slice(1)}});a.History=function(){this.handlers=[];g.bindAll(this,"checkUrl")};var p=/^[#\/]/,t=/msie [\w.]+/,n=!1;g.extend(a.History.prototype,a.Events,{interval:50,getFragment:function(a,b){if(null==a)if(this._hasPushState||b){var a=window.location.pathname,d=window.location.search;d&&(a+=d)}else a=window.location.hash;a=decodeURIComponent(a);a.indexOf(this.options.root)||(a=a.substr(this.options.root.length));return a.replace(p,"")},start:function(a){if(n)throw Error("Backbone.history has already been started");
this.options=g.extend({},{root:"/"},this.options,a);this._wantsHashChange=!1!==this.options.hashChange;this._wantsPushState=!!this.options.pushState;this._hasPushState=!(!this.options.pushState||!window.history||!window.history.pushState);var a=this.getFragment(),b=document.documentMode;if(b=t.exec(navigator.userAgent.toLowerCase())&&(!b||7>=b))this.iframe=h('<iframe src="javascript:0" tabindex="-1" />').hide().appendTo("body")[0].contentWindow,this.navigate(a);this._hasPushState?h(window).bind("popstate",
this.checkUrl):this._wantsHashChange&&"onhashchange"in window&&!b?h(window).bind("hashchange",this.checkUrl):this._wantsHashChange&&(this._checkUrlInterval=setInterval(this.checkUrl,this.interval));this.fragment=a;n=!0;a=window.location;b=a.pathname==this.options.root;if(this._wantsHashChange&&this._wantsPushState&&!this._hasPushState&&!b)return this.fragment=this.getFragment(null,!0),window.location.replace(this.options.root+"#"+this.fragment),!0;this._wantsPushState&&this._hasPushState&&b&&a.hash&&
(this.fragment=a.hash.replace(p,""),window.history.replaceState({},document.title,a.protocol+"//"+a.host+this.options.root+this.fragment));if(!this.options.silent)return this.loadUrl()},stop:function(){h(window).unbind("popstate",this.checkUrl).unbind("hashchange",this.checkUrl);clearInterval(this._checkUrlInterval);n=!1},route:function(a,b){this.handlers.unshift({route:a,callback:b})},checkUrl:function(){var a=this.getFragment();a==this.fragment&&this.iframe&&(a=this.getFragment(this.iframe.location.hash));
if(a==this.fragment||a==decodeURIComponent(this.fragment))return!1;this.iframe&&this.navigate(a);this.loadUrl()||this.loadUrl(window.location.hash)},loadUrl:function(a){var b=this.fragment=this.getFragment(a);return g.any(this.handlers,function(a){if(a.route.test(b))return a.callback(b),!0})},navigate:function(a,b){if(!n)return!1;if(!b||!0===b)b={trigger:b};var d=(a||"").replace(p,"");this.fragment==d||this.fragment==decodeURIComponent(d)||(this._hasPushState?(0!=d.indexOf(this.options.root)&&(d=
this.options.root+d),this.fragment=d,window.history[b.replace?"replaceState":"pushState"]({},document.title,d)):this._wantsHashChange?(this.fragment=d,this._updateHash(window.location,d,b.replace),this.iframe&&d!=this.getFragment(this.iframe.location.hash)&&(b.replace||this.iframe.document.open().close(),this._updateHash(this.iframe.location,d,b.replace))):window.location.assign(this.options.root+a),b.trigger&&this.loadUrl(a))},_updateHash:function(a,b,d){d?a.replace(a.toString().replace(/(javascript:|#).*$/,
"")+"#"+b):a.hash=b}});a.View=function(a){this.cid=g.uniqueId("view");this._configure(a||{});this._ensureElement();this.initialize.apply(this,arguments);this.delegateEvents()};var v=/^(\S+)\s*(.*)$/,x="model,collection,el,id,attributes,className,tagName".split(",");g.extend(a.View.prototype,a.Events,{tagName:"div",$:function(a){return this.$el.find(a)},initialize:function(){},render:function(){return this},remove:function(){this.$el.remove();return this},make:function(a,b,d){a=document.createElement(a);
b&&h(a).attr(b);d&&h(a).html(d);return a},setElement:function(a,b){this.$el=h(a);this.el=this.$el[0];!1!==b&&this.delegateEvents();return this},delegateEvents:function(a){if(a||(a=s(this,"events"))){this.undelegateEvents();for(var b in a){var d=a[b];g.isFunction(d)||(d=this[a[b]]);if(!d)throw Error('Event "'+a[b]+'" does not exist');var c=b.match(v),e=c[1],c=c[2],d=g.bind(d,this);e+=".delegateEvents"+this.cid;""===c?this.$el.bind(e,d):this.$el.delegate(c,e,d)}}},undelegateEvents:function(){this.$el.unbind(".delegateEvents"+
this.cid)},_configure:function(a){this.options&&(a=g.extend({},this.options,a));for(var b=0,d=x.length;b<d;b++){var c=x[b];a[c]&&(this[c]=a[c])}this.options=a},_ensureElement:function(){if(this.el)this.setElement(this.el,!1);else{var a=s(this,"attributes")||{};this.id&&(a.id=this.id);this.className&&(a["class"]=this.className);this.setElement(this.make(this.tagName,a),!1)}}});a.Model.extend=a.Collection.extend=a.Router.extend=a.View.extend=function(a,b){var d=m(this,a,b);d.extend=this.extend;return d};
var q={create:"POST",update:"PUT","delete":"DELETE",read:"GET"};a.sync=function(b,d,c){var e=q[b],j={type:e,dataType:"json"};c.url||(j.url=s(d,"url")||y());if(!c.data&&d&&("create"==b||"update"==b))j.contentType="application/json",j.data=JSON.stringify(d.toJSON());a.emulateJSON&&(j.contentType="application/x-www-form-urlencoded",j.data=j.data?{model:j.data}:{});if(a.emulateHTTP&&("PUT"===e||"DELETE"===e))a.emulateJSON&&(j.data._method=e),j.type="POST",j.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",
e)};"GET"!==j.type&&!a.emulateJSON&&(j.processData=!1);return h.ajax(g.extend(j,c))};a.wrapError=function(a,b,d){return function(c,e){e=c===b?e:c;a?a(b,e,d):b.trigger("error",b,e,d)}};var r=function(){},m=function(a,b,d){var c;c=b&&b.hasOwnProperty("constructor")?b.constructor:function(){a.apply(this,arguments)};g.extend(c,a);r.prototype=a.prototype;c.prototype=new r;b&&g.extend(c.prototype,b);d&&g.extend(c,d);c.prototype.constructor=c;c.__super__=a.prototype;return c},s=function(a,b){return!a||!a[b]?
null:g.isFunction(a[b])?a[b]():a[b]},y=function(){throw Error('A "url" property or function must be specified');}}).call(this);
var Lawnchair=function(c,e){if(!(this instanceof Lawnchair))return new Lawnchair(c,e);if(!JSON)throw"JSON unavailable! Include http://www.json.org/json2.js to fix.";if(arguments.length<=2&&arguments.length>0)e=typeof arguments[0]==="function"?arguments[0]:arguments[1],c=typeof arguments[0]==="function"?{}:arguments[0];else throw"Incorrect # of ctor args!";if(typeof e!=="function")throw"No callback was provided";this.record=c.record||"record";this.name=c.name||"records";var d;if(c.adapter)for(var b=
0,a=Lawnchair.adapters.length;b<a;b++){if(Lawnchair.adapters[b].adapter===c.adapter){d=Lawnchair.adapters[b].valid()?Lawnchair.adapters[b]:void 0;break}}else{b=0;for(a=Lawnchair.adapters.length;b<a;b++)if(d=Lawnchair.adapters[b].valid()?Lawnchair.adapters[b]:void 0)break}if(!d)throw"No valid adapter.";for(var g in d)this[g]=d[g];b=0;for(a=Lawnchair.plugins.length;b<a;b++)Lawnchair.plugins[b].call(this);this.init(c,e)};Lawnchair.adapters=[];
Lawnchair.adapter=function(c,e){e.adapter=c;var d="adapter valid init keys save batch get exists all remove nuke".split(" "),b=this.prototype.indexOf,a;for(a in e)if(b(d,a)===-1)throw"Invalid adapter! Nonstandard method: "+a;Lawnchair.adapters.push(e)};Lawnchair.plugins=[];Lawnchair.plugin=function(c){for(var e in c)e==="init"?Lawnchair.plugins.push(c[e]):this.prototype[e]=c[e]};
Lawnchair.prototype={isArray:Array.isArray||function(c){return Object.prototype.toString.call(c)==="[object Array]"},indexOf:function(c,e,d,b){if(c.indexOf)return c.indexOf(e);for(d=0,b=c.length;d<b;d++)if(c[d]===e)return d;return-1},lambda:function(c){return this.fn(this.record,c)},fn:function(c,e){return typeof e=="string"?new Function(c,e):e},uuid:function(){var c=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()},each:function(c){var e=
this.lambda(c);if(this.__results)for(var c=0,d=this.__results.length;c<d;c++)e.call(this,this.__results[c],c);else this.all(function(b){for(var a=0,d=b.length;a<d;a++)e.call(this,b[a],a)});return this}};
Lawnchair.adapter("webkit-sqlite",function(){var c=function(c,d){console.log("error in sqlite adaptor!",c,d)};if(!Function.prototype.bind)Function.prototype.bind=function(c){var d=[].slice,b=d.call(arguments,1),a=this,g=function(){},h=function(){return a.apply(this instanceof g?this:c||{},b.concat(d.call(arguments)))};g.prototype=a.prototype;h.prototype=new g;return h};return{valid:function(){return!!window.openDatabase},init:function(e,d){var b=this,a=b.fn(b.name,d),g="CREATE TABLE IF NOT EXISTS "+
this.name+" (id NVARCHAR(32) UNIQUE PRIMARY KEY, value TEXT, timestamp REAL)",h=function(){return a.call(b,b)};this.db=openDatabase(this.name,"1.0.0",this.name,65536);this.db.transaction(function(a){a.executeSql(g,[],h,c)})},keys:function(e){var d=this.lambda(e),b=this,a="SELECT id FROM "+this.name+" ORDER BY timestamp DESC";this.db.transaction(function(e){e.executeSql(a,[],function(a,c){if(c.rows.length==0)d.call(b,[]);else{for(var e=[],g=0,p=c.rows.length;g<p;g++)e.push(c.rows.item(g).id);d.call(b,
e)}},c)});return this},save:function(e,d){var b=this,a=e.key||b.uuid(),g="INSERT INTO "+this.name+" (value, timestamp, id) VALUES (?,?,?)",h="UPDATE "+this.name+" SET value=?, timestamp=? WHERE id=?",l=function(){if(d)e.key=a,b.lambda(d).call(b,e)},j=[new Date,a];b.exists(e.key,function(a){b.db.transaction(function(b){var d=function(a){delete a.key;j.unshift(JSON.stringify(a));b.executeSql(h,j,l,c)};a?d(e):(j.unshift(JSON.stringify(e)),b.executeSql(g,j,l,c))})});return this},batch:function(c,d){for(var b=
[],a=!1,g=this,h=function(d){b.push(d);a=b.length===c.length},l=setInterval(function(){a&&(d&&g.lambda(d).call(g,b),clearInterval(l))},200),j=0,o=c.length;j<o;j++)this.save(c[j],h);return this},get:function(e,d){var b=this,a="",a=this.isArray(e)?"SELECT id, value FROM "+this.name+" WHERE id IN ('"+e.join("','")+"')":"SELECT id, value FROM "+this.name+" WHERE id = '"+e+"'",g=function(a,c){var g=null,o=[];if(c.rows.length)for(var p=0,t=c.rows.length;p<t;p++)g=JSON.parse(c.rows.item(p).value),g.key=
c.rows.item(p).id,o.push(g);b.isArray(e)||(o=o.length?o[0]:null);d&&b.lambda(d).call(b,o)};this.db.transaction(function(b){b.executeSql(a,[],g,c)});return this},exists:function(e,d){var b="SELECT * FROM "+this.name+" WHERE id = ?",a=this,g=function(b,c){d&&a.fn("exists",d).call(a,c.rows.length>0)};this.db.transaction(function(a){a.executeSql(b,[e],g,c)});return this},all:function(e){var d=this,b="SELECT * FROM "+this.name,a=[],g=this.fn(this.name,e)||void 0,h=function(b,c){if(c.rows.length!=0)for(var e=
0,h=c.rows.length;e<h;e++){var t=JSON.parse(c.rows.item(e).value);t.key=c.rows.item(e).id;a.push(t)}g&&g.call(d,a)};this.db.transaction(function(a){a.executeSql(b,[],h,c)});return this},remove:function(e,d){var b=this,a=typeof e==="string"?e:e.key,g="DELETE FROM "+this.name+" WHERE id = ?",h=function(){d&&b.lambda(d).call(b)};this.db.transaction(function(b){b.executeSql(g,[a],h,c)});return this},nuke:function(e){var d="DELETE FROM "+this.name,b=this,a=e?function(){b.lambda(e).call(b)}:function(){};
this.db.transaction(function(b){b.executeSql(d,[],a,c)});return this}}}());(function(c){c(function(){c.support.transition=function(){var e=(document.body||document.documentElement).style;return(e.transition!==void 0||e.WebkitTransition!==void 0||e.MozTransition!==void 0||e.MsTransition!==void 0||e.OTransition!==void 0)&&{end:function(){var d;return c.browser.webkit?d="webkitTransitionEnd":c.browser.mozilla?d="transitionend":c.browser.opera&&(d="oTransitionEnd"),"TransitionEnd"}()}}()})})(window.jQuery);
(function(c){function e(){var a=this,b=setTimeout(function(){a.$element.off(c.support.transition.end);d.call(a)},500);this.$element.one(c.support.transition.end,function(){clearTimeout(b);d.call(a)})}function d(){this.$element.hide().trigger("hidden");b.call(this)}function b(b){var d=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var e=c.support.transition&&d;this.$backdrop=c('<div class="modal-backdrop '+d+'" />').appendTo(document.body);this.options.backdrop!="static"&&
this.$backdrop.click(c.proxy(this.hide,this));this.$backdrop.addClass("in");e?this.$backdrop.one(c.support.transition.end,b):b()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),c.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(c.support.transition.end,c.proxy(a,this)):a.call(this)):b&&b()}function a(){this.$backdrop.remove();this.$backdrop=null}function g(){var a=this;this.isShown&&this.options.keyboard?c(document).on("keyup.dismiss.modal",function(b){b.which==
27&&a.hide()}):this.isShown||c(document).off("keyup.dismiss.modal")}var h=function(a,b){this.options=b;this.$element=c(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",c.proxy(this.hide,this))};h.prototype={constructor:h,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var a=this;if(!this.isShown)c("body").addClass("modal-open"),this.isShown=!0,this.$element.trigger("show"),g.call(this),b.call(this,function(){var b=c.support.transition&&a.$element.hasClass("fade");
!a.$element.parent().length&&a.$element.appendTo(document.body);a.$element.show();a.$element.addClass("in");b?a.$element.one(c.support.transition.end,function(){a.$element.trigger("shown")}):a.$element.trigger("shown")})},hide:function(a){a&&a.preventDefault();if(this.isShown)this.isShown=!1,c("body").removeClass("modal-open"),g.call(this),this.$element.trigger("hide").removeClass("in"),c.support.transition&&this.$element.hasClass("fade")?e.call(this):d.call(this)}};c.fn.modal=function(a){return this.each(function(){var b=
c(this),d=b.data("modal"),e=c.extend({},c.fn.modal.defaults,typeof a=="object"&&a);d||b.data("modal",d=new h(this,e));typeof a=="string"?d[a]():e.show&&d.show()})};c.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};c.fn.modal.Constructor=h;c(function(){c("body").on("click.modal.data-api",'[data-toggle="modal"]',function(a){var b=c(this),d,e=c(b.attr("data-target")||(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),b=e.data("modal")?"toggle":c.extend({},e.data(),b.data());a.preventDefault();e.modal(b)})})})(window.jQuery);
(function(c){var e=function(d,b){this.init("tooltip",d,b)};e.prototype={constructor:e,init:function(d,b,a){var e,h;this.type=d;this.$element=c(b);this.options=this.getOptions(a);this.enabled=!0;this.options.trigger!="manual"&&(e=this.options.trigger=="hover"?"mouseenter":"focus",h=this.options.trigger=="hover"?"mouseleave":"blur",this.$element.on(e,this.options.selector,c.proxy(this.enter,this)),this.$element.on(h,this.options.selector,c.proxy(this.leave,this)));this.options.selector?this._options=
c.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(d){return d=c.extend({},c.fn[this.type].defaults,d,this.$element.data()),d.delay&&typeof d.delay=="number"&&(d.delay={show:d.delay,hide:d.delay}),d},enter:function(d){var b=c(d.currentTarget)[this.type](this._options).data(this.type);!b.options.delay||!b.options.delay.show?b.show():(b.hoverState="in",setTimeout(function(){b.hoverState=="in"&&b.show()},b.options.delay.show))},leave:function(d){var b=c(d.currentTarget)[this.type](this._options).data(this.type);
!b.options.delay||!b.options.delay.hide?b.hide():(b.hoverState="out",setTimeout(function(){b.hoverState=="out"&&b.hide()},b.options.delay.hide))},show:function(){var d,b,a,c,e,l,j;if(this.hasContent()&&this.enabled){d=this.tip();this.setContent();this.options.animation&&d.addClass("fade");l=typeof this.options.placement=="function"?this.options.placement.call(this,d[0],this.$element[0]):this.options.placement;b=/in/.test(l);d.remove().css({top:0,left:0,display:"block"}).appendTo(b?this.$element:document.body);
a=this.getPosition(b);c=d[0].offsetWidth;e=d[0].offsetHeight;switch(b?l.split(" ")[1]:l){case "bottom":j={top:a.top+a.height,left:a.left+a.width/2-c/2};break;case "top":j={top:a.top-e,left:a.left+a.width/2-c/2};break;case "left":j={top:a.top+a.height/2-e/2,left:a.left-c};break;case "right":j={top:a.top+a.height/2-e/2,left:a.left+a.width}}d.css(j).addClass(l).addClass("in")}},setContent:function(){var d=this.tip();d.find(".tooltip-inner").html(this.getTitle());d.removeClass("fade in top bottom left right")},
hide:function(){function d(){var a=setTimeout(function(){b.off(c.support.transition.end).remove()},500);b.one(c.support.transition.end,function(){clearTimeout(a);b.remove()})}var b=this.tip();b.removeClass("in");c.support.transition&&this.$tip.hasClass("fade")?d():b.remove()},fixTitle:function(){var d=this.$element;(d.attr("title")||typeof d.attr("data-original-title")!="string")&&d.attr("data-original-title",d.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},
getPosition:function(d){return c.extend({},d?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var d,b=this.$element,a=this.options;return d=b.attr("data-original-title")||(typeof a.title=="function"?a.title.call(b[0]):a.title),d=d.toString().replace(/(^\s*|\s*$)/,""),d},tip:function(){return this.$tip=this.$tip||c(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.$element=
null,this.options=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()}};c.fn.tooltip=function(d){return this.each(function(){var b=c(this),a=b.data("tooltip"),g=typeof d=="object"&&d;a||b.data("tooltip",a=new e(this,g));typeof d=="string"&&a[d]()})};c.fn.tooltip.Constructor=e;c.fn.tooltip.defaults={animation:!0,delay:0,selector:!1,placement:"top",trigger:"hover",
title:"",template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'}})(window.jQuery);
(function(c){var e=function(d,b){this.init("popover",d,b)};e.prototype=c.extend({},c.fn.tooltip.Constructor.prototype,{constructor:e,setContent:function(){var d=this.tip(),b=this.getTitle(),a=this.getContent();d.find(".popover-title")[c.type(b)=="object"?"append":"html"](b);d.find(".popover-content > *")[c.type(a)=="object"?"append":"html"](a);d.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var d,b=this.$element,
a=this.options;return d=b.attr("data-content")||(typeof a.content=="function"?a.content.call(b[0]):a.content),d=d.toString().replace(/(^\s*|\s*$)/,""),d},tip:function(){return this.$tip||(this.$tip=c(this.options.template)),this.$tip}});c.fn.popover=function(d){return this.each(function(){var b=c(this),a=b.data("popover"),g=typeof d=="object"&&d;a||b.data("popover",a=new e(this,g));typeof d=="string"&&a[d]()})};c.fn.popover.Constructor=e;c.fn.popover.defaults=c.extend({},c.fn.tooltip.defaults,{placement:"right",
content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>'})})(window.jQuery);
(function(c){var e=function(d){c(d).on("click",'[data-dismiss="alert"]',this.close)};e.prototype={constructor:e,close:function(d){function b(){h.remove();h.trigger("closed")}var a=c(this),e=a.attr("data-target"),h;e||(e=a.attr("href"),e=e&&e.replace(/.*(?=#[^\s]*$)/,""));h=c(e);h.trigger("close");d&&d.preventDefault();h.length||(h=a.hasClass("alert")?a:a.parent());h.removeClass("in");c.support.transition&&h.hasClass("fade")?h.on(c.support.transition.end,b):b()}};c.fn.alert=function(d){return this.each(function(){var b=
c(this),a=b.data("alert");a||b.data("alert",a=new e(this));typeof d=="string"&&a[d].call(b)})};c.fn.alert.Constructor=e;c(function(){c("body").on("click.alert.data-api",'[data-dismiss="alert"]',e.prototype.close)})})(window.jQuery);
(function(c){var e=function(d,b){this.$element=c(d);this.options=c.extend({},c.fn.button.defaults,b)};e.prototype={constructor:e,setState:function(d){var b=this.$element,a=b.data(),c=b.is("input")?"val":"html";d+="Text";a.resetText||b.data("resetText",b[c]());b[c](a[d]||this.options[d]);setTimeout(function(){d=="loadingText"?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)},toggle:function(){var d=this.$element.parent('[data-toggle="buttons-radio"]');
d&&d.find(".active").removeClass("active");this.$element.toggleClass("active")}};c.fn.button=function(d){return this.each(function(){var b=c(this),a=b.data("button"),g=typeof d=="object"&&d;a||b.data("button",a=new e(this,g));d=="toggle"?a.toggle():d&&a.setState(d)})};c.fn.button.defaults={loadingText:"loading..."};c.fn.button.Constructor=e;c(function(){c("body").on("click.button.data-api","[data-toggle^=button]",function(d){c(d.target).button("toggle")})})})(window.jQuery);
(function(c){function e(a){var b=a||window.event,d=[].slice.call(arguments,1),e=0,j=0,o=0,a=c.event.fix(b);a.type="mousewheel";b.wheelDelta&&(e=b.wheelDelta/120);b.detail&&(e=-b.detail/3);o=e;b.axis!==void 0&&b.axis===b.HORIZONTAL_AXIS&&(o=0,j=-1*e);b.wheelDeltaY!==void 0&&(o=b.wheelDeltaY/120);b.wheelDeltaX!==void 0&&(j=-1*b.wheelDeltaX/120);d.unshift(a,e,j,o);return(c.event.dispatch||c.event.handle).apply(this,d)}var d=["DOMMouseScroll","mousewheel"];if(c.event.fixHooks)for(var b=d.length;b;)c.event.fixHooks[d[--b]]=
c.event.mouseHooks;c.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=d.length;a;)this.addEventListener(d[--a],e,!1);else this.onmousewheel=e},teardown:function(){if(this.removeEventListener)for(var a=d.length;a;)this.removeEventListener(d[--a],e,!1);else this.onmousewheel=null}};c.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(window.jQuery);
(function(c){var e=function(a){this.startRect=a;this.top=a.top;this.left=a.left;this.width=a.width;this.height=a.height;this.scale=1};e.prototype.applyConstraints=function(){};e.prototype.getZoom=function(){return this.height/this.startRect.height};e.prototype.getOffsetX=function(){return(this.left-this.startRect.left)/this.scale};e.prototype.getOffsetY=function(){return(this.top-this.startRect.top)/this.scale};e.prototype.pan=function(a,b){this.top+=b;this.left+=a};e.prototype.zoom=function(a,b,
d){a=(this.width+d)/this.startRect.width;b=a*this.startRect.height;this.width=a*this.startRect.width;this.height=b;this.scale=a;this.top-=0;this.left-=0};e.prototype.applyScale=function(a,b,d){d>4&&(d=4);d<0.1&&(d=0.1);a=d*this.startRect.height;this.width=d*this.startRect.width;this.height=a;this.scale=d;this.top-=0;this.left-=0};var d=function(a){var b="scale("+a.getZoom()+") ";b+="translate("+a.getOffsetX()+"px, "+a.getOffsetY()+"px)";return b},b=function(a,b,d,c,e){var g=null;a.mousewheel(function(a,
h){a.preventDefault();b.zoom(a.offsetX,a.offsetY,h*e.scaleRate);g&&clearTimeout(g);d();g=setTimeout(function(){c()},35)})},a=function(a,b,d,c){var e=!1,g=0,n=0;a.mousedown(function(a){e=!0;g=a.clientX;n=a.clientY;d()}).mouseup(function(){e=!1;c()}).mousemove(function(a){if(e)b.pan(a.clientX-g,a.clientY-n),b.applyConstraints(),g=a.clientX,n=a.clientY})},g=function(a,b,d,c){a.on("gesturestart",function(a){a.preventDefault();d()}).on("gestureend",function(a){a.preventDefault();c()}).on("gesturechange",
function(a){a.preventDefault();b.applyScale(0,0,a.originalEvent.scale);d()})};c.fn.zoomAndScale=function(h){h=c.extend({},c.fn.zoomAndScale.defaults,h);return this.each(function(){var l=c(this),j=c("body"),o=(l.width()-j.width())/2,p=(l.height()-j.height())/2+20;o>0&&l.css({position:"relative",right:o+"px",top:"-"+p+"px"});var t=!0,o={top:0,left:0,width:l.width(),height:l.height()},n=new e(o);n.applyScale(0,0,j.height()/l.height()*0.9);l.css("-webkit-transform",d(n));l.css("-webkit-transform",d(n));
var v=function(){t||(l.css("-webkit-transform",d(n)),setTimeout(v,h.frameRate))},j=function(){t&&(t=!1,v())},o=function(){t=!0};a(l,n,j,o,h);b(l,n,j,o,h);g(l,n,j,o,h)})};c.fn.zoomAndScale.defaults={frameRate:30,scaleRate:30}})(window.jQuery);
(function(){function c(b,a,g){g===void 0&&(g=a);if(e(b)==="array"){var h=[];if(b[0]!=null)if(d=="msie"){a.setProperty("SelectionLanguage","XPath");for(var g=g.selectNodes(b[0]),l;l=g.nextNode();)h.push(c(b[1],a,l))}else if(d=="node"){g=g.find(b[0]);for(l=0;l<g.length;l++)h.push(c(b[1],a,g[l]))}else for(g=a.evaluate(b[0],g,Jath.resolver,XPathResult.ANY_TYPE,null);l=g.iterateNext();)h.push(c(b[1],a,l));else for(l=1;l<b.length;l++)h.push(c(b[l],a,g));b=h}else if(e(b)==="object"){l={};for(h in b)l[h]=
c(b[h],a,g);b=l}else h=g,d=="msie"?(a.setProperty("SelectionLanguage","XPath"),b=e(b)=="string"&&b.substring(0,1)!=Jath.literalChar?h.selectSingleNode(b).text:b.substring(1)):d=="node"?(require("sys").puts(b),b=h.get(b).text()):b=e(b)=="string"&&b[0]!=Jath.literalChar?a.evaluate(b,h,Jath.resolver,XPathResult.STRING_TYPE,null).stringValue:b.substring(1);return b}function e(b){var a=typeof b;a==="object"&&(b?typeof b.length==="number"&&!b.propertyIsEnumerable("length")&&typeof b.splice==="function"&&
(a="array"):a="null");return a}Jath={};Jath.parse=c;Jath.resolver=null;Jath.literalChar=":";var d;typeof WScript!="undefined"?d="msie":typeof process!="undefined"?(d="node",require("libxmljs"),exports.parse=c):d=navigator.userAgent.toLowerCase().indexOf("msie")>-1?"msie":"standards"})();
function URI(c){c||(c="");c=c.match(/^(?:([^:\/?\#]+):)?(?:\/\/([^\/?\#]*))?([^?\#]*)(?:\?([^\#]*))?(?:\#(.*))?/);this.scheme=c[1]||null;this.authority=c[2]||null;this.path=c[3]||null;this.query=c[4]||null;this.fragment=c[5]||null}URI.prototype.toString=function(){var c="";this.scheme&&(c+=this.scheme+":");this.authority&&(c+="//"+this.authority);this.path&&(c+=this.path);this.query&&(c+="?"+this.query);this.fragment&&(c+="#"+this.fragment);return c};
(function(){function c(d){if(!d)return"";d=d.replace(/\/\.\//g,"/");for(d=d.replace(/\/\.$/,"/");d.match(e);)d=d.replace(e,"/");for(d=d.replace(/\/([^\/]*)\/\.\.$/,"/");d.match(/\/\.\.\//);)d=d.replace(/\/\.\.\//,"/");return d}var e=/\/((?!\.\.\/)[^\/]*)\/\.\.\//;URI.prototype.resolve=function(d){var b=new URI;if(this.scheme)b.scheme=this.scheme,b.authority=this.authority,b.path=c(this.path),b.query=this.query;else{if(this.authority)b.authority=this.authority,b.path=c(this.path),b.query=this.query;
else{if(this.path){if(this.path.charAt(0)==="/")b.path=c(this.path);else{var a;a=this.path;var e=/^(.*)\//;a=d.authority&&!d.path?"/"+a:d.path.match(e)[0]+a;b.path=a;b.path=c(b.path)}b.query=this.query}else b.path=d.path,b.query=this.query?this.query:d.query;b.authority=d.authority}b.scheme=d.scheme}b.fragment=this.fragment;return b}})();
(function(){if(typeof JSIO=="object"){var c=Error("JSIO is already defined");c.source="JSIO.core.js";throw c;}JSIO={version:"1.3 2011May10",decimalToHexString:function(c,d){c<0&&(c=4294967295+c+1);var b=c.toString(16).toUpperCase();d&&(b="00000000"+b,b=b.substring(b.length-d));return b},FileType:{Text:0,Binary:1,XML:2,Unknown:3}};JSIO.guessFileType=function(c){if(c=="makefile")return JSIO.FileType.Text;if(c=="mimetype")return JSIO.FileType.Text;var d=c.lastIndexOf(".");if(d<=0)return JSIO.FileType.Unknown;
c=c.substring(d);return c==".zip"?JSIO.FileType.Binary:c==".xlsx"?JSIO.FileType.Binary:c==".docx"?JSIO.FileType.Binary:c==".dll"?JSIO.FileType.Binary:c==".obj"?JSIO.FileType.Binary:c==".pdb"?JSIO.FileType.Binary:c==".exe"?JSIO.FileType.Binary:c==".xml"?JSIO.FileType.XML:c==".xsl"?JSIO.FileType.XML:c==".csproj"?JSIO.FileType.XML:c==".vbproj"?JSIO.FileType.XML:c==".shfbproj"?JSIO.FileType.XML:c==".resx"?JSIO.FileType.XML:c==".xslt"?JSIO.FileType.XML:c==".sln"?JSIO.FileType.Text:c==".htm"?JSIO.FileType.Text:
c==".html"?JSIO.FileType.Text:c==".js"?JSIO.FileType.Text:c==".vb"?JSIO.FileType.Text:c==".txt"?JSIO.FileType.Text:c==".rels"?JSIO.FileType.Text:c==".css"?JSIO.FileType.Text:c==".cs"?JSIO.FileType.Text:c==".ncx"?JSIO.FileType.Text:c==".xhtml"?JSIO.FileType.Text:c==".opf"?JSIO.FileType.Text:JSIO.FileType.Unknown};JSIO.stringOfLength=function(c,d){for(var b="",a=0;a<d;a++)b+=String.fromCharCode(c);return b};JSIO.formatByteArray=function(c){for(var d="0000  ",b="",a=0;a<c.length;a++)a!==0&&a%16===0&&
(d+="    "+b+"\n"+JSIO.decimalToHexString(a,4)+"  ",b=""),d+=JSIO.decimalToHexString(c[a],2)+" ",b+=c[a]>=32&&c[a]<=126?String.fromCharCode(c[a]):".";b.length>0&&(d+=JSIO.stringOfLength(32,(a%16>0?(16-a%16)*3:0)+4)+b);return d};JSIO.htmlEscape=function(c){return c.replace(RegExp("&","g"),"&amp;").replace(RegExp("<","g"),"&lt;").replace(RegExp(">","g"),"&gt;").replace(RegExp("\u0013","g"),"<br/>").replace(RegExp("\u0010","g"),"<br/>")}})();
(function(){typeof JSIO!=="object"&&(JSIO={});if(typeof JSIO.version!=="string")JSIO.version="1.3 2011May10";else if(JSIO.version.length<3||JSIO.version.substring(0,3)!=="1.3")JSIO.version+=" 1.3 2011May10";var c=function(){this.position=0};c.prototype.readToEnd=function(){for(var b=[],a=this.readByte();a!==null;)b.push(a),a=this.readByte();return b};c.prototype.beginReadToEnd=function(b){var a=[],d=this,c=function(){for(var e=0,j=d.readByte();j!==null;){a.push(j);e++;if(e>=1024)break;j=d.readByte()}j!==
null?typeof setTimeout=="undefined"?c():setTimeout(c,1):b(a)};c();return null};c.prototype.readBytes=function(b){for(var a=[],d=0;d<b;++d)a.push(this.readByte());return a};c.prototype.beginReadBytes=function(b,a){var d=[],c=this,e=b,j=function(){for(var b=0,p=c.readByte();e>0&&p!==null;){d.push(p);b++;e--;if(b>=1024)break;p=c.readByte()}e>0&&p!==null?setTimeout(j,1):a(d)};j();return null};JSIO._ByteReaderBase=c;c=function(b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");
a.source="JSIO.ArrayReader";throw a;}this.position=0;this.array=b;this._typename="JSIO.ArrayReader";this._version="1.3 2011May10";return this};c.prototype=new JSIO._ByteReaderBase;c.prototype.readByte=function(){if(this.position>=this.array.length)return null;var b=this.array[this.position];this.position++;return b};var e=function(b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");a.source="JSIO.StreamReader";throw a;}if(!b)throw a=Error("you must pass a non-null stream."),
a.source="JSIO.StreamReader",a;this.stream=b;this.position=0;this._typeName="JSIO.StreamReader";this._version="1.3 2011May10";this.length=b.getLength();return this};e.prototype=new JSIO._ByteReaderBase;e.prototype.readByte=function(){if(this.position>=this.length)return null;var b=this.stream.readByteAt(this.position);this.position++;return b};var d=function(b,a,d){if(!(this instanceof arguments.callee)){var c=Error("you must use new to instantiate this class");c.source="JSIO.StreamSegmentReader";
throw c;}if(!b)throw c=Error("you must pass a non-null stream."),c.source="JSIO.StreamSegmentReader",c;this.stream=b;this.position=a||0;this.limit=d?a+d:0;this._typeName="JSIO.StreamSegmentReader";this._version="1.3 2011May10";return this};d.prototype=new JSIO._ByteReaderBase;d.prototype.readByte=function(){if(this.limit!==0&&this.position>=this.limit)return null;var b=this.stream.readByteAt(this.position);this.position++;return b};JSIO.ArrayReader=c;JSIO.StreamReader=e;JSIO.StreamSegmentReader=d})();
(function(){if(typeof JSIO!=="object"||typeof JSIO.version!=="string"||JSIO.version.length<3||JSIO.version.substring(0,3)!=="1.3"){var c=Error("This extension requires JSIO.core.js v1.3");c.source="JSIO.BinaryUrlStream.js";throw c;}if(typeof JSIO._ByteReaderBase!=="function")throw c=Error("This class requires JSIO.BasicByteReaders.js"),c.source="JSIO.BinaryUrlStream.js",c;/msie/i.test(navigator.userAgent)&&!/opera/i.test(navigator.userAgent)&&document.write("<\!-- IEBinaryToArray_ByteStr --\>\r\n<script type='text/vbscript'>\r\nFunction IEBinaryToArray_ByteStr(Binary)\r\n   IEBinaryToArray_ByteStr = CStr(Binary)\r\nEnd Function\r\nFunction IEBinaryToArray_ByteStr_Last(Binary)\r\n   Dim lastIndex\r\n   lastIndex = LenB(Binary)\r\n   if lastIndex mod 2 Then\r\n           IEBinaryToArray_ByteStr_Last = Chr( AscB( MidB( Binary, lastIndex, 1 ) ) )\r\n   Else\r\n           IEBinaryToArray_ByteStr_Last = \"\"\r\n   End If\r\nEnd Function\r\n<\/script>\r\n");
var e=function(d,b,a){switch(d){case 1:d=Error('Failed to load "'+b+'"');break;case 2:d=Error("Error: EOF reached");break;case 3:d=Error("Error: cannot instantiate XMLHttpRequest");break;case 4:d=Error("Error: cannot seek");break;default:d=Error("Unknown Error.")}if(a)d.message=a;d.source="JSIO.BinaryUrlStream";throw d;},c=function(d,b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");a.source="JSIO.BinaryUrlStream.ctor";throw a;}this.callback=b;this.readByteAt=
null;this.fileSize=-1;this.filePointer=0;this.req=null;this._typename="JSIO.BinaryUrlStream";this._version="1.3 2011May10";this.status="-none-";var a=function(a){var b=this,d=function(a){for(var b={},d=0;d<256;d++)for(var c=0;c<256;c++)b[String.fromCharCode(d+c*256)]=String.fromCharCode(d)+String.fromCharCode(c);d=IEBinaryToArray_ByteStr(a);a=IEBinaryToArray_ByteStr_Last(a);return d.replace(/[\s\S]/g,function(a){return b[a]})+a};this.req=function(){if(window.XMLHttpRequest)return new window.XMLHttpRequest;
else try{return new ActiveXObject("MSXML2.XMLHTTP")}catch(a){return null}}();this.req.open("GET",a,!0);this.req.setRequestHeader("Accept-Charset","x-user-defined");this.req.onreadystatechange=function(){if(b.req.readyState==4)if(b.status="Status: "+b.req.status,b.req.status==200){var c=d(b.req.responseBody);b.fileSize=c.length-1;b.fileSize<0&&e(1,a,"after converting");b.readByteAt=function(a){return c.charCodeAt(a)&255};typeof b.callback=="function"&&b.callback(b)}else e(1,a,"http status code "+b.req.status)};
this.req.send()},c=function(a){var b=this;this.req=new XMLHttpRequest;this.req.open("GET",a,!0);this.req.onreadystatechange=function(){if(b.req.readyState==4)if(b.status="Status: "+b.req.status,b.req.status==200){var d=b.req.responseText;b.fileSize=d.length;b.readByteAt=function(a){return d.charCodeAt(a)&255};typeof b.callback=="function"&&b.callback(b)}else e(1,a)};this.req.overrideMimeType("text/plain; charset=x-user-defined");this.req.send(null)};/msie/i.test(navigator.userAgent)&&!/opera/i.test(navigator.userAgent)?
a.apply(this,[d]):c.apply(this,[d])};JSIO.SeekOrigin={Current:1,Begin:2};c.prototype=new JSIO._ByteReaderBase;c.prototype.getLength=function(){return this.fileSize};c.prototype.getPosition=function(){return this.filePointer};c.prototype.seek=function(d,b,a){typeof a!="undefined"&&a.verbose>1&&a.status.push("INFO: Seek "+d+" bytes, origin("+b+") start(0x"+JSIO.decimalToHexString(this.filePointer)+"/"+this.filePointer+")");switch(b){case JSIO.SeekOrigin.Current:this.seek(this.filePointer+d,JSIO.SeekOrigin.Begin);
break;case JSIO.SeekOrigin.Begin:d<0?this.filePointer=0:d>this.getLength()?e(2):this.filePointer=d;break;default:e(4)}typeof a!="undefined"&&a.verbose>1&&a.status.push("INFO: Seek end(0x"+JSIO.decimalToHexString(this.filePointer)+"/"+this.filePointer+")");return this.filePointer};c.prototype.read=function(d){if(d===0)return[];if(d<0)throw d=Error("invalid read length."),d.source="BinaryUrlStream.read()",d;for(var b=this.filePointer,a=[],c=b;c<b+d;c++)a.push(this.readByteAt(c));this.filePointer+=d;
return a};c.prototype.readByte=function(){var d=this.read(1);return d.length==1?d[0]:null};c.prototype.beginRead=function(d,b){d===0&&b(0);if(d<0){var a=Error("invalid read length.");a.source="BinaryUrlStream.beginRead()";throw a;}var c=[],e=this,l=d,j=function(){for(var a=0,d=e.filePointer;l>0;)if(c.push(e.readByteAt(a+d)),a++,l--,a>=1024)break;e.filePointer+=a;l>0?setTimeout(j,1):b(c)};j();return null};c.prototype.readNumber=function(d,b){for(var a=d||1,c=b||this.filePointer,e=0,l=c+a;l>c;l--)e=
e*256+this.readByteAt(l-1);this.filePointer=c+a;return e};c.prototype.readString=function(d,b){for(var a=d||1,c=b||this.filePointer,e="",l=c+a;c<l;c++)e+=String.fromCharCode(this.readByteAt(c));this.filePointer+=a;return e};c.prototype.readNullTerminatedString=function(c){for(var c=c||this.filePointer,b="",a="",e=0,h=String.fromCharCode(this.readByteAt(c+e));h!==null;)a+=h,e++,e>=1024&&(b+=a,a="",c+=e,this.filePointer+=e,e=0),h=String.fromCharCode(this.readByteAt(c+e));this.filePointer=c+e;return b+
a};c.prototype.beginReadNullTerminatedString=function(c,b){var a=b||this.filePointer,e="",h="",l=this,j=function(){for(var b=0,p=String.fromCharCode(l.readByteAt(a+b));p!==null;){h+=p;b++;if(b>=1024){e+=h;h="";a+=b;l.filePointer+=b;b=0;break}p=String.fromCharCodet(l.readByteAt(i))}l.filePointer=a+b;p!==null?setTimeout(j,1):c(e+h)};j();return null};JSIO.BinaryUrlStream=c})();
(function(){if(typeof JSIO!=="object"||typeof JSIO.version!=="string"){var c=Error("This extension requires JSIO.core.js v1.3");c.source="JSIO.TextDecoder.js";throw c;}if(JSIO.version.length<3||JSIO.version.substring(0,3)!=="1.3")throw c=Error("This extension requires JSIO.core.js v1.3"),c.source="JSIO.TextDecoder.js",c;if(typeof JSIO._ByteReaderBase!=="function")throw c=Error("This class requires JSIO.BasicByteReaders.js"),c.source="JSIO.TextDecoder.js",c;c=function(b){if(!(this instanceof arguments.callee)){var a=
Error("you must use new to instantiate this class");a.source="JSIO.TextDecoder.Default.ctor";throw a;}this.byteReader=b;this._version="1.3 2011May10";this._typename="JSIO.TextDecoder.Default";return this};c.prototype.readChar=function(){var b=this.byteReader.readByte();return b<0?null:String.fromCharCode(b)};var e=function(b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");a.source="JSIO.TextDecoder.Utf16.ctor";throw a;}this.byteReader=b;this.bomState=
0;this._version="1.3 2011May10";this._typename="JSIO.TextDecoder.Utf16";return this};e.prototype.readChar=function(){var b=this.byteReader.readByte();if(b<0)return null;var a=this.byteReader.readByte();if(a<0)throw b=Error("Incomplete UTF16 character"),b.source="JSIO.TextDecoder.Utf16.readChar()",b;if(this.bomState===0&&b+a==509){this.bomState=a==254?1:2;b=this.byteReader.readByte();if(b<0)return null;a=this.byteReader.readByte();if(a<0)throw b=Error("Incomplete UTF16 character"),b.source="JSIO.TextDecoder.Utf16.readChar()",
b;}else this.bomState=1;return String.fromCharCode(this.bomState==1?a<<8|b:b<<8|a)};var d=function(b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");a.source="JSIO.TextDecoder.Utf8.ctor";throw a;}this.byteReader=b;this.waitBom=!0;this.strict=!1;this.pendingChar=null;this._version="1.3 2011May10";this._typename="JSIO.TextDecoder.Utf8";return this};d.prototype.readChar=function(){var b=null;do{if(this.pendingChar!==null)b=this.pendingChar,this.pendingChar=
null;else{var a=this.byteReader.readByte();if(a===null)return null;if((a&128)===0)b=String.fromCharCode(a);else{var c=192,b=5;do{if((a&(c>>1|128))==c)break;c=c>>1|128;--b}while(b>=0);if(b>0){a&=(1<<b)-1;for(c=5;c>=b;--c){var d=this.byteReader.readByte();if((d&192)!=128)throw b=Error("Invalid sequence character"),b.source=this._typename+".readChar",b;a=a<<6|d&63}a<=65535?b=a==65279&&this.waitBom?null:String.fromCharCode(a):(b=a-65536,a=55296|b>>10&1023,this.pendingChar=String.fromCharCode(56320|b&
1023),b=String.fromCharCode(a))}else if(this.strict)throw b=Error("Invalid character"),b.source=this._typename+".readChar",b;else b=String.fromCharCode(a)}}this.waitBom=!1}while(b===null);return b};JSIO.TextDecoder={Default:c,Utf16:e,Utf8:d}})();
(function(){if(typeof JSIO.TextDecoder.Utf8!=="function"){var c=Error("This class requires JSIO.TextDecoder.js");c.source="JSIO.TextReader.js";throw c;}c=function(c){if(!(this instanceof arguments.callee)){var d=Error("you must use new to instantiate this class");d.source="JSIO.TextReader.ctor";throw d;}this.decoder=c;this._version="1.3 2011May10";this._typename="JSIO.TextReader";this.unreads=[]};c.prototype.readChar=function(){return this.unreads.length>0?this.unreads.pop():this.decoder.readChar()};
c.prototype.read=function(c){var d="";for(vari=0;i<c;i++){var b=this.readChar();b!==null?d+=b:i=c}return d};c.prototype.unreadChar=function(c){this.unreads.push(c)};c.prototype.readToEnd=function(){for(var c="",d="",b=0,a=this.readChar();a!==null;)d+=a,b++,b>=1024&&(c+=d,d="",b=0),a=this.readChar();return c+d};c.prototype.beginReadToEnd=function(c){var d="",b="",a=this,g=function(){for(var h=0,l=a.readChar();l!==null;){b+=l;h++;if(h>=1024){d+=b;b="";break}l=a.readChar()}l!==null?setTimeout(g,1):c(d+
b)};g();return null};c.prototype.readLine=function(){var c="",d=this.readChar();if(d===null)return null;for(;d!="\r"&&d!="\n";)if(c+=d,d=this.readChar(),d===null)return c;d=="\r"&&(d=this.readChar(),d!==null&&d!="\n"&&this.unreadChar(d));return c};JSIO.TextReader=c})();
(function(){if(typeof JSIO._ByteReaderBase!=="function"){var c=Error("This extension requires JSIO.BasicByteReaders.js");c.source="JSIO.Crc32.js";throw c;}JSIO.crc32Table=null;JSIO.crc32Polynomial=3988292384;var e=function(){if(!JSIO.crc32Table){JSIO.crc32Table=Array(256);for(var b=0;b<256;b++){for(var a=b,c=0;c<8;c++)a&1?a=JSIO.crc32Polynomial^a>>>1:a>>>=1;JSIO.crc32Table[b]=a}}};JSIO.computeCrc32=function(b){e();var a=4294967295,c=b.length;if(typeof b=="object")for(var d=0;d<c;d++)a=JSIO.crc32Table[a&
255^b[d]]^a>>>8;else for(d=0;d<c;d++)a=JSIO.crc32Table[a&255^b.charCodeAt(d)]^a>>>8;a^=4294967295;a<0&&(a+=4294967296);return a};c=function(){if(!(this instanceof arguments.callee)){var b=Error("you must use new to instantiate this class");b.source="JSIO.Crc32.ctor";throw b;}e();this._typename="JSIO.Crc32";this._version="1.3 2011May10";this._runningCrc32=4294967295};c.prototype.slurpByte=function(b){var a=this._runningCrc32;this._runningCrc32=a>>>8^JSIO.crc32Table[b^a&255]};c.prototype.result=function(){var b=
this._runningCrc32^4294967295;b<0&&(b+=4294967296);return b};var d=function(b){if(!(this instanceof arguments.callee)){var a=Error("you must use new to instantiate this class");a.source="JSIO.Crc32Reader.ctor";throw a;}this._byteReader=b;this._typename="JSIO.Crc32Reader";this._version="1.3 2011May10";this._crc32=new JSIO.Crc32};d.prototype=new JSIO._ByteReaderBase;d.prototype.readByte=function(){var b=this._byteReader.readByte();b!==null&&this._crc32.slurpByte(b);return b};d.prototype.crc32=function(){return this._crc32.result()};
JSIO.Crc32=c;JSIO.Crc32Reader=d})();
(function(){if(typeof JSIO._ByteReaderBase!=="function"){var c=Error("This class requires JSIO.BasicByteReaders.js");c.source="JSIO.InflatingReader.js";throw c;}var e=function(a){if(!(this instanceof arguments.callee)){var b=Error("you must use new to instantiate this class");b.source="InflatingReader._InternalBitReader.ctor";throw b;}this.bits=this.bitsLength=0;this.byteReader=a;this._typeName="JSIO.InflatingReader._InternalBitReader";this._version="1.3 2011May10"};e.prototype.readBit=function(){if(this.bitsLength===
0){var a=this.byteReader.readByte();if(a===null)throw a=Error("Unexpected end of stream"),a.source=this._typeName+".readBit",a;this.bits=a;this.bitsLength=8}a=(this.bits&1)!==0;this.bits>>=1;--this.bitsLength;return a};e.prototype.align=function(){this.bitsLength=0};e.prototype.readLSB=function(a){for(var b=0,c=0;c<a;++c)this.readBit()&&(b|=1<<c);return b};e.prototype.readMSB=function(a){for(var b=0,c=0;c<a;++c)this.readBit()?b=b<<1|1:b<<=1;return b};var c=function(a){if(!(this instanceof arguments.callee)){var b=
Error("you must use new to instantiate this class");b.source="JSIO.InflatingReader.ctor";throw b;}this._byteReader=a;this._bitReader=new e(a);this._buffer=[];this._state=this._bufferPosition=0;this._blockFinal=!1;this._typeName="JSIO.InflatingReader";this._version="1.3 2011May10";return this},d=null,b=null,a=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],g=function(a){for(var b=0,c=Array(a.length),d=a[0],b=1;b<a.length;b++)d<a[b]&&(d=a[b]);for(var e=Array(d+1),b=0;b<=d;b++)e[b]=0;for(b=0;b<a.length;b++)++e[a[b]];
var g=Array(d+1),b=0;e[0]=0;for(var j=1;j<=d;j++)b=b+e[j-1]<<1,g[j]=b;for(b=0;b<c.length;b++)d=a[b],d!==0&&(c[b]=g[d],g[d]++);return c},h=function(a,b){for(var c=[],d=0;d<a.length;++d)if(b[d]>0){var e={};e.bits=a[d];e.length=b[d];e.index=d;c.push(e)}return l(c,0,0)},l=function(a,b,c){if(a.length===0)return null;for(var d=[],e=[],g={isLeaf:!1},j=0;j<a.length;++j)if(a[j].length==c&&a[j].bits==b){g.isLeaf=!0;g.index=a[j].index;break}else(a[j].bits>>a[j].length-c-1&1)>0?e.push(a[j]):d.push(a[j]);if(!g.isLeaf)g.zero=
l(d,b<<1,c+1),g.one=l(e,b<<1|1,c+1);return g},j=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],o=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],p=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],t=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];c.prototype=new JSIO._ByteReaderBase;c.prototype._decodeItem=function(){var c,e;if(this._state==2)return null;if(this._state===
0)switch(this._blockFinal=this._bitReader.readBit(),e=this._bitReader.readLSB(2),e){case 0:this._bitReader.align();var l=this._bitReader.readLSB(16);e=this._bitReader.readLSB(16);if((l&~e)!=l)throw e=Error("Invalid block type 0 length"),e.source="JSIO.InflatingReader._decodeItem",e;e={itemType:0};e.array=Array(l);for(c=0;c<l;++c){var q=this._byteReader.readByte();if(q<0)throw e=Error("Incomplete block"),e.source="JSIO.InflatingReader._decodeItem",e;e.array[c]=q}if(this._blockFinal)this._state=2;return e;
case 1:this._codesTree=d;this._distancesTree=b;this._state=1;break;case 2:c=this._bitReader;e=c.readLSB(5)+257;for(var l=c.readLSB(5)+1,r=c.readLSB(4)+4,q=Array(19),m=0,m=0;m<q.length;++m)q[m]=0;for(m=0;m<r;++m)q[a[m]]=c.readLSB(3);r=g(q);r=h(r,q);for(q=[];q.length<e+l;){for(m=r;!m.isLeaf;)m=c.readBit()?m.one:m.zero;m=m.index;if(m<=15)q.push(m);else if(m==16)for(var m=c.readLSB(2)+3,s=0;s<m;++s)q.push(q[q.length-1]);else if(m==17){m=c.readLSB(3)+3;for(s=0;s<m;++s)q.push(0)}else if(m==18){m=c.readLSB(7)+
11;for(s=0;s<m;++s)q.push(0)}}c=q.slice(0,e);r=g(c);e=q.slice(e,e+l);l=g(e);c=h(r,c);e=h(l,e);this._codesTree=c;this._distancesTree=e;this._state=1;break;default:throw e=Error("Invalid block type ("+e+")"),e.source="JSIO.InflatingReader._decodeItem",e;}e={};for(c=this._codesTree;!c.isLeaf;)c=this._bitReader.readBit()?c.one:c.zero;if(c.index<256)e.itemType=2,e.symbol=c.index;else if(c.index>256){c=c.index;if(c>285)throw e=Error("Invalid length code"),e.source="JSIO.InflatingReader._decodeItem",e;l=
j[c-257];o[c-257]>0&&(l+=this._bitReader.readLSB(o[c-257]));for(c=this._distancesTree;!c.isLeaf;)c=this._bitReader.readBit()?c.one:c.zero;c=c.index;q=p[c];t[c]>0&&(q+=this._bitReader.readLSB(t[c]));e.itemType=3;e.distance=q;e.length=l}else e.itemType=1,this._state=this._blockFinal?2:0;return e};c.prototype.readByte=function(){for(;this._bufferPosition>=this._buffer.length;){var a=this._decodeItem();if(a===null)return null;switch(a.itemType){case 0:this._buffer=this._buffer.concat(a.array);break;case 2:this._buffer.push(a.symbol);
break;case 3:for(var b=this._buffer.length-a.distance,c=0;c<a.length;c++)this._buffer.push(this._buffer[b++])}}a=this._buffer[this._bufferPosition++];if(this._bufferPosition>49152){b=this._buffer.length-32768;if(b>this._bufferPosition)b=this._bufferPosition;this._buffer.splice(0,b);this._bufferPosition-=b}this.position++;return a};(function(){for(var a=Array(288),c=Array(288),e=0,e=0;e<=143;e++)a[e]=48+e,c[e]=8;for(e=144;e<=255;e++)a[e]=400+e-144,c[e]=9;for(e=256;e<=279;e++)a[e]=0+e-256,c[e]=7;for(e=
280;e<=287;e++)a[e]=192+e-280,c[e]=8;d=h(a,c);a=Array(32);c=Array(32);for(e=0;e<=31;e++)a[e]=e,c[e]=5;b=h(a,c)})();JSIO.InflatingReader=c})();
(function(){function c(b){this.zipfile=b;this._typename="ZipEntry";this._version=e;this._crcCalculator=null}var e="1.26 2011Aug07";if(typeof JSIO.BinaryUrlStream!="function"){var d=Error("This extension requires JSIO.BinaryUrlStream.js v1.3");d.source="Zipfile.js";throw d;}if(typeof JSIO.TextDecoder!=="object")throw d=Error("This extension requires JSIO.TextDecoder.js"),d.source="Zipfile.js",d;if(typeof JSIO.TextReader!=="function")throw d=Error("This extension requires JSIO.TextReader.js"),d.source=
"Zipfile.js",d;if(typeof JSIO.Crc32!=="function")throw d=Error("This extension requires JSIO.Crc32.js"),d.source="Zipfile.js",d;if(typeof JSIO.InflatingReader!=="function")throw d=Error("This extension requires JSIO.InflatingReader.js"),d.source="Zipfile.js",d;c.prototype.extract=function(b,a){this.contentType=JSIO.guessFileType(this.name);var a=a||this.contentType==JSIO.FileType.Text||this.contentType==JSIO.FileType.XML,c=this;if(this.compressionMethod!==0&&this.compressionMethod!=8){var d=Error("Unsupported compression method: "+
this.compressionMethod);d.source="ZipEntry.extract()";throw d;}d=a?this.openTextReader():this.openBinaryReader();d.zipEntryName=c.name;if(typeof b!="function")return d=d.readToEnd(),this.verifyCrc32(),d;d.beginReadToEnd(function(a){try{c.verifyCrc32(),b(c,a)}catch(d){b(c,d)}});return null};c.prototype.openBinaryReader=function(){var b=new JSIO.StreamSegmentReader(this.zipfile.binaryStream,this.offset+this.lengthOfHeader,this.compressedSize);this.compressionMethod!==0&&(b=new JSIO.InflatingReader(b));
return this._crcCalculator=new JSIO.Crc32Reader(b)};c.prototype.openTextReader=function(b){var a=this.openBinaryReader(),b=b||JSIO.TextDecoder.Utf8,c=new b;b.apply(c,[a]);b=new JSIO.TextReader(c);return c._parent=b};c.prototype.verifyCrc32=function(){var b=this._crcCalculator.crc32(),a=!1;this.crc32!=b?this.zipfile.status.push("WARNING: CRC check failed: entry("+this.name+") computed("+JSIO.decimalToHexString(b,8)+") expected("+JSIO.decimalToHexString(this.crc32,8)+") "):(a=!0,this.zipfile.verbose>
2&&this.zipfile.status.push("INFO: CRC check ok: 0x"+JSIO.decimalToHexString(this.crc32,8)));return a};ZipFile=function(b,a,d){function h(){var a=j.binaryStream.getPosition(),b=j.binaryStream.readNumber(4);if(b==ZipFile.Signatures.DirEntry)return j.verbose>0&&j.status.push("INFO: at offset 0x"+JSIO.decimalToHexString(a)+", found start of Zip Directory."),null;if(b!=ZipFile.Signatures.Entry)return j.status.push("WARNING: at offset 0x"+JSIO.decimalToHexString(a)+", found unexpected signature: 0x"+JSIO.decimalToHexString(b)),
null;var d=new c(j);d.offset=a;d.versionNeeded=j.binaryStream.readNumber(2);d.bitField=j.binaryStream.readNumber(2);d.compressionMethod=j.binaryStream.readNumber(2);var b=j.binaryStream.readNumber(4),e;if(b==65535||b===0)e=new Date(1995,0,1,0,0,0,0);else{var g=b&65535,h=(b&4294901760)>>16,b=1980+((h&65024)>>9),a=((h&480)>>5)-1;h&=31;var l=(g&63488)>>11,r=(g&2016)>>5,g=(g&31)*2;g>=60&&(r++,g=0);r>=60&&(l++,r=0);l>=24&&(h++,l=0);var m=!1;try{e=new Date(b,a,h,l,r,g,0),m=!0}catch(s){if(b==1980&&(a===
0||h===0))try{e=new Date(1980,0,1,l,r,g,0),m=!0}catch(y){try{e=new Date(1980,0,1,0,0,0,0),m=!0}catch(k){}}else try{for(;b<1980;)b++;for(;b>2030;)b--;for(;a<1;)a++;for(;a>12;)a--;for(;h<1;)h++;for(;h>28;)h--;for(;r<0;)r++;for(;r>59;)r--;for(;g<0;)g++;for(;g>59;)g--;e=new Date(b,a-1,h,l,r,g,0);m=!0}catch(f){}}if(!m)throw d=Error("bad date/time value in this zip file."),d.source="ZipFile.ReadZipEntry",d;}d.lastModified=e;if((d.bitField&1)==1)return j.status.push("This zipfile uses Encryption, which is not supported by ZipFile.js."),
null;d.utf8=(d.bitField&2048)==2048;d.usesTrailingDescriptor=(d.bitField&8)==8;d.crc32=j.binaryStream.readNumber(4);d.compressedSize=j.binaryStream.readNumber(4);d.uncompressedSize=j.binaryStream.readNumber(4);if(d.compressedSize==4294967295||d.uncompressedSize==4294967295)return j.status.push("This zipfile uses ZIP64, which is not supported by ZipFile.js"),null;b=j.binaryStream.readNumber(2);a=j.binaryStream.readNumber(2);j.status.push("INFO: filename length= "+b);e=30+b+a;d.utf8?(j.status.push("INFO: before filename, position= 0x"+
JSIO.decimalToHexString(j.binaryStream.getPosition())),g=new JSIO.StreamSegmentReader(j.binaryStream,j.binaryStream.getPosition(),b),g=new JSIO.TextDecoder.Utf8(g),g=new JSIO.TextReader(g),d.name=g.readToEnd(),j.binaryStream.seek(b,JSIO.SeekOrigin.Current,j),j.status.push("INFO: after filename, position= 0x"+JSIO.decimalToHexString(j.binaryStream.getPosition()))):d.name=j.binaryStream.readString(b);d.extra=j.binaryStream.read(a);j.verbose>1&&j.status.push("INFO: at offset 0x"+JSIO.decimalToHexString(d.offset)+
", found entry '"+d.name+"' fnl("+b+") efl("+a+")");a>0&&j.verbose>0&&j.status.push("INFO: entry "+d.name+" has "+a+" bytes of extra metadata (ignored)");b=0;if(d.usesTrailingDescriptor){a=j.binaryStream.getPosition();for(b=j.binaryStream.readNumber(4);b!=ZipFile.Signatures.DataDescriptor;)j.binaryStream.seek(-3,JSIO.SeekOrigin.Current),b=j.binaryStream.readNumber(4);d.crc32=j.binaryStream.readNumber(4);d.compressedSize=j.binaryStream.readNumber(4);d.uncompressedSize=j.binaryStream.readNumber(4);
b=16;j.binaryStream.seek(a,JSIO.SeekOrigin.Begin)}d.lengthOfHeader=e;d.totalEntrySize=d.lengthOfHeader+d.compressedSize;j.verbose>1&&j.status.push("INFO: seek 0x"+JSIO.decimalToHexString(d.compressedSize)+" ("+d.compressedSize+") bytes");j.binaryStream.seek(d.compressedSize+b,JSIO.SeekOrigin.Current,j);return d}if(!(this instanceof arguments.callee)){var l=Error("you must use new to instantiate this class");l.source="ZipFile.ctor";throw l;}this.verbose=d||0;this.entries=[];this.entryNames=[];this.status=
[];this._version=e;this._typename="ZipFile";var j=this;this.binaryStream=new JSIO.BinaryUrlStream(b,function(b){try{if(b.req.status==200)if(j.binaryStream.readNumber(4)!=ZipFile.Signatures.Entry)j.status.push("WARNING: this file does not appear to be a zip file");else{j.binaryStream.seek(0,JSIO.SeekOrigin.Begin);if(j.entryNames.length===0)for(var c;(c=h())!==null;)j.entries.push(c),j.entryNames.push(c.name);j.verbose>0&&j.status.push("INFO: read "+j.entries.length+" entries")}else j.status.push("ERROR: the URL could not be read ("+
b.req.status+" "+b.req.statusText+")");a(j)}catch(d){j.status.push("Exception: "+d.message),a(j)}});return this};ZipFile.Signatures={Entry:67324752,EndOfCentralDirectory:101010256,DirEntry:33639248,DataDescriptor:134695760};ZipFile.Version=e;ZipFile.EncryptionAlgorithm={None:0,PkzipWeak:1,WinZipAes:2}})();
(function(c){function e(b,a,d,e){var a=b.text().split(a),l="";a.length&&(c(a).each(function(a,b){l+='<span class="'+d+(a+1)+'">'+b+"</span>"+e}),b.empty().append(l))}var d={init:function(){return this.each(function(){e(c(this),"","char","")})},words:function(){return this.each(function(){e(c(this)," ","word"," ")})},lines:function(){return this.each(function(){e(c(this).children("br").replaceWith("eefec303079ad17405c889e092e105b0").end(),"eefec303079ad17405c889e092e105b0","line","")})}};c.fn.lettering=
function(b){if(b&&d[b])return d[b].apply(this,[].slice.call(arguments,1));else if(b==="letters"||!b)return d.init.apply(this,[].slice.call(arguments,0));c.error("Method "+b+" does not exist on jQuery.lettering");return this}})(jQuery);
(function(c,e,d,b){var a=defaults={resizing:!0,lazyTime:150,resizeOversizedElements:!0},g=function(a,b,d){h(a,b,d);var g=!1;c(e).resize(function(){g||(g=!0,setTimeout(function(){h(a,b,d);g=!1},d.lazyTime))})},h=function(a,b){b=b.slice(0);a.css("display","none");var c,d=b[0];c=a.clone();d.css("position")==="static"&&d.css("position","relative");d.empty();d.append(c.children());d.children().first().css("margin-top","0");c=l(d);d.children().last().css("margin-bottom","0");b.shift();return b.length>0?
h(c,b):c},l=function(d,e,g){e===b&&(e=d);var h=c("<div></div>"),n=!1;d.children().each(function(a,b){b=c(b);n?(b.detach(),h.append(c("<span> </span>")),h.append(b)):b.position().top+b.outerHeight(!0)>=e.height()&&(b.detach(),n=b)});if(n)if(g||(n.contents().filter(function(){return this.nodeType===3}).wrap("<span></span").parent().lettering("words"),g=!0),n.children().length){d.append(n);var g=l(n,e,g),v=n.clone();v.empty();v.append(g.children());h.prepend(v)}else h.prepend(n);n&&d.children().length===
0&&(a.resizeOversizedElements&&n.css({"max-width":e.innerWidth(),"max-height":e.innerHeight()}),d.append(n));return h};c.fn.regions=function(a,b){b=c.extend(defaults,b);typeof a==="string"||a instanceof jQuery?(a instanceof jQuery||(a=c(a)),regionsArray=c.makeArray(a),a=c.map(regionsArray,function(a){return c(a)})):a=c.map(a,function(a){return typeof a==="string"?c(a):a});b.resizing?g(c(this),a,b):h(c(this),a,b);return this}})(jQuery,window,document);
