Readium.Models.EbookBase=Backbone.Model.extend({initialize:function(){var a=this,b=this.get("package_doc_path");this.packageDocument=new Readium.Models.PackageDocument({url:b});this.packageDocument.on("change:spine_position",this.spinePositionChangedHandler,this);this.packageDocument.on("change:spine",function(){a.packageDocument.set({spine_position:0},{silent:!0});a.set("has_toc",!!a.packageDocument.getTocItem())});this.packageDocument.fetch({dataType:"xml"});this.on("change:num_pages",this.adjustCurrentPage,
this)},defaults:{font_size:10,current_page:[1],num_pages:0,two_up:!1,full_screen:!1,toolbar_visible:!0,toc_visible:!1},toggleTwoUp:function(){var a=this.get("two_up"),b=this.get("current_page"),c=[];a?c[0]=b[0]===0?1:b[0]:b[0]%2===0?(c[0]=b[0],c[1]=b[0]+1):(c[0]=b[0]-1,c[1]=b[0]);this.set({two_up:!a,current_page:c})},toggleFullScreen:function(){this.set({full_screen:!this.get("full_screen")})},increaseFont:function(){this.set({font_size:this.get("font_size")+1})},decreaseFont:function(){this.set({font_size:this.get("font_size")-
1})},toggleToc:function(){this.set("toc_visible",!this.get("toc_visible"))},prevPage:function(){var a=this.get("current_page"),b=a[0]-1;a[0]<=1?this.packageDocument.goToPrevSection():this.get("two_up")?this.set("current_page",[b-1,b]):this.set("current_page",[b])},nextPage:function(){var a=this.get("current_page"),b=a[a.length-1]+1;if(a[a.length-1]>=this.get("num_pages"))this.packageDocument.goToNextSection();else return this.get("two_up")?this.set("current_page",[b,b+1]):this.set("current_page",
[b])},goToFirstPage:function(){this.get("two_up")?this.set("current_page",[0,1]):this.set("current_page",[1])},goToLastPage:function(){var a=this.get("num_pages");this.get("two_up")?this.set("current_page",[a-1,a]):this.set("current_page",[a])},savePosition:function(){Readium.Utils.setCookie(_properties.key,_packageDocument.getPosition(),365)},resolvePath:function(a){var b=this.packageDocument.file_path,a=a.indexOf("../")===0?a.substr(3):a,c=b.lastIndexOf("/");return b.substr(0,c)+"/"+a},adjustCurrentPage:function(){var a=
this.get("current_page"),b=this.get("num_pages");this.get("two_up");a[a.length-1]>b&&this.goToLastPage()},goToNextSection:function(){this.packageDocument.hasNextSection()&&this.packageDocument.goToNextSection()},goToPrevSection:function(){this.packageDocument.hasPrevSection()&&this.packageDocument.goToPrevSection()},getSectionText:function(a,b){var c=this.packageDocument.currentSection();Readium.FileSystemApi(function(d){d.readTextFile(resolvePath(c),a,b)})},goToHref:function(a){this.packageDocument.goToHref(a)},
changPageNumber:function(a){var b=this.get("current_page"),c=[],d=a-b[b.length-1];d>0&&(d=0);for(var e=0;e<b.length;e++)c[e]=b[e]+d;this.set({num_pages:a,current_page:c})},spinePositionChangedHandler:function(){var a=this,b=this.packageDocument.currentSection().get("href"),c=this.packageDocument.resolveUri(b),b=this.resolvePath(b);this.set("current_section_url",c);$.ajax({url:b,accept:"xml",cache:!0,success:function(b){a.set("current_content",b)},error:function(){alert("Error: unable to fetch spine item");
window.router.navigate("/",{silent:!0})}})},getToc:function(){var a=this.packageDocument.getTocItem();return a?Readium.Models.Toc.getToc(a,{file_path:this.resolvePath(a.get("href")),book:this}):null},goToPage:function(a){this.get("two_up")?a%2===0?this.set("current_page",[a,a+1]):this.set("current_page",[a-1,a]):this.set("current_page",[a])}});
Readium.Models.ReflowableEbook=Readium.Models.EbookBase.extend({isFixedLayout:!1,initialize:function(){Readium.Models.EbookBase.prototype.initialize.call(this)},CreatePaginator:function(){var a=localStorage.READIUM_OPTIONS;return(a&&JSON.parse(a)||{singleton:{}}).singleton.paginate_everything?new Readium.Views.ReflowablePaginationView({model:this}):new Readium.Views.ScrollingPaginationView({model:this})}});
Readium.Models.AppleFixedEbook=Readium.Models.EbookBase.extend({isFixedLayout:!0,defaults:{font_size:10,current_page:[0,1],num_pages:0,two_up:!1,full_screen:!1,toolbar_visible:!0},initialize:function(){Readium.Models.EbookBase.prototype.initialize.call(this);this.on("change:current_content",this.parseMetaTags,this)},CreatePaginator:function(){return new Readium.Views.FixedPaginationView({model:this})},buildSectionJSON:function(a){var b={};b.width=this.get("meta_width");b.height=this.get("meta_height");
b.uri=this.packageDocument.resolveUri(a.get("href"));return b},getAllSections:function(){for(var a=this.packageDocument.getResolvedSpine(),b=[],c=0;c<a.length;c++)b.push(this.buildSectionJSON(a[c]));return b},parseViewportTag:function(a){for(var a=a.getAttribute("content"),a=a.replace(/\s/g,""),a=a.split(","),b={},c,d=0;d<a.length;d++)c=a[d].split("="),c.length===2&&(b[c[0]]=c[1]);b.width=parseFloat(b.width);b.height=parseFloat(b.height);return b},parseMetaTags:function(){var a=this.get("current_content");
typeof a==="string"&&(a=(new window.DOMParser).parseFromString(a,"text/xml"));if(a=$("meta[name]='viewport'",a)[0])a=this.parseViewportTag(a),this.set({meta_width:a.width,meta_height:a.height});this.packageDocument.off("change:spine_position");this.off("current_content");this.trigger("first_render_ready")},spinePositionChangedHandler:function(){Readium.Models.EbookBase.prototype.spinePositionChangedHandler.call(this);this.goToPage(this.packageDocument.get("spine_position"))}});
